export interface EconomicEvent {
  id: string;
  time: string;
  indicator: string;
  indicatorKo?: string;
  importance: "Low" | "Medium" | "High";
  previous: string | null;
  forecast: string | null;
  actual: string | null;
  unit: string | null;
  country: string;
  category: string;
  definitionEn: string;
  definitionKo: string;
  impactEn: string;
  impactKo: string;
  correlationEn: string;
  correlationKo: string;
  counterIndicatorEn: string;
  counterIndicatorKo: string;
}

// Note: All times stored in UTC. KST = UTC+9 (Korea has no DST).
// US events: before Mar 8 2026 -> EST (UTC-5), so 8:30AM ET = 13:30 UTC
//            after Mar 8 2026  -> EDT (UTC-4), so 8:30AM ET = 12:30 UTC

const EVENTS: EconomicEvent[] = [
  // ===== FEBRUARY 2026 =====
  {
    id: "2026-02-27-pce",
    time: "2026-02-27T13:30:00Z",
    indicator: "Core PCE Price Index (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.3%",
    actual: "0.3%",
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Core Personal Consumption Expenditures (PCE) Price Index measures changes in prices paid by consumers for goods and services, excluding volatile food and energy. The Fed's preferred inflation measure.",
    definitionKo: "근원 개인소비지출(PCE) 물가지수는 변동성이 큰 식품과 에너지를 제외한 소비자가 구매하는 상품 및 서비스의 가격 변동을 측정합니다. 연준이 선호하는 인플레이션 지표입니다.",
    impactEn: "High impact on Fed rate decisions. Higher than expected is hawkish (USD bullish, Bonds bearish, Stocks bearish). Lower readings may trigger rate cut expectations.",
    impactKo: "연준의 금리 결정에 큰 영향을 미칩니다. 예상보다 높으면 매파적(달러 강세, 채권 약세, 주식 약세)으로 해석됩니다. 낮은 수치는 금리 인하 기대를 촉발할 수 있습니다.",
    correlationEn: "Closely watched alongside CPI. High Core PCE → Likely Rate Hike → Downward pressure on Tech stocks and Growth stocks. Inverse to Bonds.",
    correlationKo: "CPI와 함께 면밀히 관찰됩니다. 높은 근원 PCE → 금리 인상 가능성 → 기술주 및 성장주 하락 압력. 채권과 반비례 관계.",
    counterIndicatorEn: "10-Year Treasury Yield, NASDAQ",
    counterIndicatorKo: "10년 국채 수익률, 나스닥"
  },
  {
    id: "2026-02-27-sentiment",
    time: "2026-02-27T15:00:00Z",
    indicator: "UMich Consumer Sentiment (Final)",
    importance: "Medium",
    previous: "71.1",
    forecast: "71.8",
    actual: null,
    unit: "index",
    country: "USA",
    category: "Consumer",
    definitionEn: "The University of Michigan Consumer Sentiment Index rates the relative level of current and future economic conditions. Based on a monthly survey of ~500 consumers.",
    definitionKo: "미시간대 소비자심리지수는 현재 및 미래 경제 상황의 상대적 수준을 평가합니다. 약 500명의 소비자를 대상으로 한 월간 설문 조사를 기반으로 합니다.",
    impactEn: "Moderate impact. Rising sentiment signals stronger future consumer spending, which supports GDP growth and corporate earnings.",
    impactKo: "중간 정도의 영향. 심리 지수 상승은 향후 소비자 지출 증가를 시사하며, GDP 성장과 기업 실적을 지지합니다.",
    correlationEn: "Positive correlation with Retail Sales and Consumer Spending. High sentiment → Increased retail activity → Positive for Consumer Discretionary stocks.",
    correlationKo: "소매 판매 및 소비자 지출과 양의 상관관계가 있습니다. 높은 심리 지수 → 소매 활동 증가 → 소비재 주식에 긍정적.",
    counterIndicatorEn: "Savings Rate, Credit Card Debt",
    counterIndicatorKo: "저축률, 신용카드 부채"
  },

  // ===== MARCH 2026 =====
  {
    id: "2026-03-02-ism-mfg",
    time: "2026-03-02T15:00:00Z",
    indicator: "ISM Manufacturing PMI",
    importance: "High",
    previous: "52.6",
    forecast: "51.7",
    actual: "52.4",
    unit: "index",
    country: "USA",
    category: "Manufacturing",
    definitionEn: "The ISM Manufacturing PMI (Purchasing Managers' Index) is a monthly indicator of economic activity in the US manufacturing sector. A reading above 50 indicates expansion.",
    definitionKo: "ISM 제조업 PMI(구매관리자지수)는 미국 제조업 부문의 월간 경제 활동 지표입니다. 50 이상이면 경기 확장을 나타냅니다.",
    impactEn: "High impact. A reading above 50 is bullish for equities and the USD. Below 50 signals contraction and is bearish.",
    impactKo: "큰 영향을 미칩니다. 50 이상이면 주식과 달러에 강세 신호. 50 미만은 수축을 나타내며 약세 신호입니다.",
    correlationEn: "Leading indicator for GDP. Strong ISM Mfg → Supply chain activity up → Materials and Industrials stocks rally.",
    correlationKo: "GDP의 선행 지표입니다. 강한 ISM 제조업 → 공급망 활동 증가 → 소재 및 산업재 주식 상승.",
    counterIndicatorEn: "Industrial Production, Factory Orders",
    counterIndicatorKo: "산업생산, 공장주문"
  },
  {
    id: "2026-03-04-ism-svc",
    time: "2026-03-04T15:00:00Z",
    indicator: "ISM Services PMI",
    importance: "High",
    previous: "52.8",
    forecast: "53.0",
    actual: null,
    unit: "index",
    country: "USA",
    category: "Services",
    definitionEn: "The ISM Services PMI measures economic activity in the US services sector, which accounts for roughly 80% of the economy. A reading above 50 indicates expansion.",
    definitionKo: "ISM 서비스 PMI는 미국 경제의 약 80%를 차지하는 서비스 부문의 경제 활동을 측정합니다. 50 이상이면 경기 확장을 나타냅니다.",
    impactEn: "Very high impact as services dominate the US economy. Strong reading supports employment and consumer activity.",
    impactKo: "서비스업이 미국 경제를 지배하므로 매우 큰 영향을 미칩니다. 강한 수치는 고용과 소비자 활동을 지지합니다.",
    correlationEn: "Directly linked to Jobs data. Strong Services PMI → More hiring in services → Lower Unemployment Rate.",
    correlationKo: "고용 데이터와 직접적으로 연결됩니다. 강한 서비스 PMI → 서비스업 고용 증가 → 실업률 하락.",
    counterIndicatorEn: "Initial Jobless Claims, Unemployment Rate",
    counterIndicatorKo: "신규 실업수당 청구 건수, 실업률"
  },
  {
    id: "2026-03-06-nfp",
    time: "2026-03-06T13:30:00Z",
    indicator: "Non-Farm Payrolls (NFP)",
    importance: "High",
    previous: "143K",
    forecast: "170K",
    actual: null,
    unit: "K",
    country: "USA",
    category: "Employment",
    definitionEn: "Non-Farm Payrolls measures the change in the number of employed people during the previous month, excluding the farming industry. Released on the first Friday of each month by the Bureau of Labor Statistics.",
    definitionKo: "비농업 고용지수는 농업을 제외한 지난 한 달 동안 고용된 인원수의 변화를 측정합니다. 매달 첫째 주 금요일에 노동통계국에서 발표합니다.",
    impactEn: "One of the most market-moving reports. Strong NFP = Economic strength, but may lead to rate hike fears. Weak NFP = Rate cut hopes.",
    impactKo: "시장에 가장 큰 영향을 미치는 지표 중 하나입니다. 강한 NFP = 경제적 강세, 하지만 금리 인상 우려로 이어질 수 있습니다. 약한 NFP = 금리 인하 기대감.",
    correlationEn: "Strong NFP → Strong USD → Weak Gold. Also closely linked to Fed rate decisions. High jobs = inflation risk = hawkish Fed.",
    correlationKo: "강한 NFP → 달러 강세 → 금 약세. 연준 금리 결정과도 밀접하게 연결됩니다. 높은 고용 = 인플레이션 위험 = 매파적 연준.",
    counterIndicatorEn: "Initial Jobless Claims, Fed Funds Rate",
    counterIndicatorKo: "신규 실업수당 청구 건수, 연방기금금리"
  },
  {
    id: "2026-03-06-unemp",
    time: "2026-03-06T13:30:00Z",
    indicator: "Unemployment Rate",
    importance: "High",
    previous: "4.0%",
    forecast: "4.0%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Employment",
    definitionEn: "The Unemployment Rate measures the percentage of the total work force that is unemployed and actively seeking employment. Released alongside NFP on the first Friday of each month.",
    definitionKo: "실업률은 총 노동력 중 실업 상태에 있으며 적극적으로 취업을 원하는 사람의 비율을 측정합니다. 매달 첫째 주 금요일에 NFP와 함께 발표됩니다.",
    impactEn: "Higher unemployment = Economic weakness = Rate cut expectations = Bullish for Bonds, initially mixed for Stocks.",
    impactKo: "높은 실업률 = 경제 약세 = 금리 인하 기대 = 채권에 강세, 주식에는 초기에 혼조세.",
    correlationEn: "Inverse relationship with NFP. Rising unemployment → Rate cuts → Bonds rally → Eventually Stocks recover.",
    correlationKo: "NFP와 역의 관계. 실업률 상승 → 금리 인하 → 채권 상승 → 결국 주식 회복.",
    counterIndicatorEn: "Non-Farm Payrolls, Job Openings (JOLTS)",
    counterIndicatorKo: "비농업 고용지수, 구인/이직(JOLTS)"
  },
  {
    id: "2026-03-11-cpi",
    time: "2026-03-11T12:30:00Z",
    indicator: "Consumer Price Index (CPI) (MoM)",
    importance: "High",
    previous: "0.5%",
    forecast: "0.3%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Consumer Price Index (CPI) measures the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services. A key inflation gauge.",
    definitionKo: "소비자물가지수(CPI)는 도시 소비자들이 구매하는 소비재 및 서비스의 가격 변화를 시간에 따라 측정합니다. 핵심 인플레이션 지표입니다.",
    impactEn: "Extremely high impact. Hot CPI → Rate hike fears → Sell Bonds, Sell Growth stocks. Cool CPI → Rate cut hopes → Buy Bonds, Buy Tech.",
    impactKo: "매우 큰 영향을 미칩니다. 높은 CPI → 금리 인상 우려 → 채권 매도, 성장주 매도. 낮은 CPI → 금리 인하 기대 → 채권 매수, 기술주 매수.",
    correlationEn: "High CPI → Likely Rate Hike → Downward pressure on Tech stocks (high P/E). Gold benefits from moderate inflation. Very high CPI hurts all assets.",
    correlationKo: "높은 CPI → 금리 인상 가능성 → 기술주(높은 P/E) 하락 압력. 금은 적당한 인플레이션에서 혜택. 매우 높은 CPI는 모든 자산에 악영향.",
    counterIndicatorEn: "Fed Funds Rate, Core PCE",
    counterIndicatorKo: "연방기금금리, 근원 PCE"
  },
  {
    id: "2026-03-11-core-cpi",
    time: "2026-03-11T12:30:00Z",
    indicator: "Core CPI (YoY)",
    importance: "High",
    previous: "3.3%",
    forecast: "3.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "Core CPI excludes food and energy prices, providing a cleaner measure of underlying inflation trends. The Fed closely monitors this to separate temporary price shocks from persistent inflation.",
    definitionKo: "근원 CPI는 식품과 에너지 가격을 제외하여 기저 인플레이션 추세를 더 명확하게 측정합니다. 연준은 일시적 가격 충격과 지속적 인플레이션을 구분하기 위해 이를 면밀히 주시합니다.",
    impactEn: "Fed's primary focus for rate decisions. Sticky Core CPI means rates stay higher for longer, pressuring growth stocks.",
    impactKo: "연준의 금리 결정에 주요 초점. 끈적한 근원 CPI는 금리가 더 오래 높은 상태를 유지함을 의미하며, 성장주에 압력을 가합니다.",
    correlationEn: "Closely tied to wages. High Core CPI + High Wages → Wage-price spiral risk → Extended tight monetary policy.",
    correlationKo: "임금과 밀접하게 연관됩니다. 높은 근원 CPI + 높은 임금 → 임금-물가 나선 위험 → 장기 긴축 통화 정책.",
    counterIndicatorEn: "Average Hourly Earnings, Shelter Costs",
    counterIndicatorKo: "평균 시간당 임금, 주거비"
  },
  {
    id: "2026-03-12-ppi",
    time: "2026-03-12T12:30:00Z",
    indicator: "Producer Price Index (PPI) (MoM)",
    importance: "Medium",
    previous: "0.4%",
    forecast: "0.3%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The PPI measures the average change in selling prices received by domestic producers for their output. It is a leading indicator of consumer price inflation.",
    definitionKo: "생산자물가지수(PPI)는 국내 생산자가 자신의 생산물에 대해 받는 판매 가격의 평균 변화를 측정합니다. 소비자 물가 인플레이션의 선행 지표입니다.",
    impactEn: "Moderate impact. High PPI signals future CPI increases as producers pass costs to consumers.",
    impactKo: "중간 정도의 영향. 높은 PPI는 생산자가 비용을 소비자에게 전가함에 따라 미래 CPI 상승을 예고합니다.",
    correlationEn: "Leading indicator for CPI. Rising PPI → Supply chain cost pressures → Future consumer price increases → Inflation risk.",
    correlationKo: "CPI의 선행 지표입니다. PPI 상승 → 공급망 비용 압박 → 미래 소비자 물가 상승 → 인플레이션 위험.",
    counterIndicatorEn: "Consumer Price Index (CPI)",
    counterIndicatorKo: "소비자물가지수(CPI)"
  },
  {
    id: "2026-03-17-retail",
    time: "2026-03-17T12:30:00Z",
    indicator: "Retail Sales (MoM)",
    importance: "High",
    previous: "-0.9%",
    forecast: "0.5%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Consumer",
    definitionEn: "Retail Sales measures the total receipts at stores that sell merchandise and related services to final consumers. It is the primary gauge of consumer spending, which accounts for ~70% of US GDP.",
    definitionKo: "소매 판매는 최종 소비자에게 상품 및 관련 서비스를 판매하는 매장의 총 수입을 측정합니다. 미국 GDP의 약 70%를 차지하는 소비자 지출의 주요 측정 지표입니다.",
    impactEn: "High impact. Strong retail sales = Healthy consumer = GDP growth = Positive for discretionary stocks.",
    impactKo: "큰 영향을 미칩니다. 강한 소매 판매 = 건강한 소비자 = GDP 성장 = 소비재 주식에 긍정적.",
    correlationEn: "Strong retail = GDP up → Inflation concern → Rate pressure. Weak retail = Recession fears → Flight to safety (Bonds, Gold).",
    correlationKo: "강한 소매 = GDP 상승 → 인플레이션 우려 → 금리 압박. 약한 소매 = 경기침체 우려 → 안전자산 선호(채권, 금).",
    counterIndicatorEn: "Consumer Confidence, Savings Rate",
    counterIndicatorKo: "소비자신뢰지수, 저축률"
  },
  {
    id: "2026-03-18-fomc-day1",
    time: "2026-03-18T14:00:00Z",
    indicator: "FOMC Meeting (Day 1)",
    importance: "High",
    previous: "4.25-4.50%",
    forecast: "4.25-4.50%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The Federal Open Market Committee (FOMC) meets 8 times per year to set the Federal Funds Rate, the benchmark interest rate that influences all US borrowing costs.",
    definitionKo: "연방공개시장위원회(FOMC)는 연간 8번 모여 미국의 모든 차입 비용에 영향을 미치는 기준 금리인 연방기금금리를 결정합니다.",
    impactEn: "Extremely high market impact. Rate decisions directly affect mortgage rates, bond yields, and the cost of capital for businesses.",
    impactKo: "시장에 매우 큰 영향을 미칩니다. 금리 결정은 주택담보대출 금리, 국채 수익률, 기업 자본 비용에 직접적으로 영향을 줍니다.",
    correlationEn: "Rate Hike → Strong USD, Weak Bonds, Weak Growth Stocks. Rate Cut → Weak USD, Strong Bonds, Strong Tech/Growth.",
    correlationKo: "금리 인상 → 강한 달러, 약한 채권, 약한 성장주. 금리 인하 → 약한 달러, 강한 채권, 강한 기술주/성장주.",
    counterIndicatorEn: "Core PCE, Unemployment Rate, Fed Dot Plot",
    counterIndicatorKo: "근원 PCE, 실업률, 연준 점도표"
  },
  {
    id: "2026-03-19-fomc-decision",
    time: "2026-03-19T18:00:00Z",
    indicator: "FOMC Rate Decision & Press Conference",
    importance: "High",
    previous: "4.25-4.50%",
    forecast: "4.25-4.50%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The FOMC announces its decision on the Federal Funds Rate, followed by a press conference from the Fed Chair. The press conference often moves markets more than the rate decision itself.",
    definitionKo: "FOMC가 연방기금금리 결정을 발표하고 연준 의장의 기자회견이 이어집니다. 기자회견은 종종 금리 결정 자체보다 시장을 더 크게 움직입니다.",
    impactEn: "The most market-moving event of the month. Even if rates stay unchanged, the tone (hawkish/dovish) and dot plot projections can cause massive market swings.",
    impactKo: "한 달 중 시장에 가장 큰 영향을 미치는 이벤트입니다. 금리가 변하지 않더라도 어조(매파/비둘기파)와 점도표 전망이 대규모 시장 급등락을 일으킬 수 있습니다.",
    correlationEn: "Hawkish surprise → All risk assets sell off. Dovish surprise → Risk-on rally across Stocks, Crypto, High-yield bonds.",
    correlationKo: "매파적 서프라이즈 → 모든 위험 자산 매도. 비둘기파적 서프라이즈 → 주식, 암호화폐, 하이일드 채권 전반에 걸친 위험 선호 랠리.",
    counterIndicatorEn: "2-Year Treasury Yield, VIX, S&P 500",
    counterIndicatorKo: "2년 국채 수익률, VIX, S&P 500"
  },
  {
    id: "2026-03-27-pce",
    time: "2026-03-27T12:30:00Z",
    indicator: "Core PCE Price Index (MoM)",
    importance: "High",
    previous: "0.3%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Fed's preferred inflation measure. Core PCE excludes food and energy, giving a stable view of underlying price trends. Released monthly by the Bureau of Economic Analysis.",
    definitionKo: "연준이 선호하는 인플레이션 측정 지표입니다. 근원 PCE는 식품과 에너지를 제외하여 기저 가격 추세를 안정적으로 파악합니다. 경제분석국에서 매월 발표합니다.",
    impactEn: "Directly influences Fed policy. Prints above 0.2% MoM sustain rate-hold/hike bias. Below 0.2% opens the door to rate cuts.",
    impactKo: "연준 정책에 직접적인 영향을 미칩니다. 전월 대비 0.2% 초과 시 금리 동결/인상 편향이 지속됩니다. 0.2% 미만 시 금리 인하 가능성이 열립니다.",
    correlationEn: "High Core PCE → Rates higher for longer → Pressure on high-duration assets (NASDAQ, long-term bonds).",
    correlationKo: "높은 근원 PCE → 장기 높은 금리 → 장기 자산(나스닥, 장기 채권)에 압박.",
    counterIndicatorEn: "Fed Funds Rate, 10Y-2Y Treasury Spread",
    counterIndicatorKo: "연방기금금리, 10년-2년 국채 금리 스프레드"
  },
  {
    id: "2026-03-31-conf-board",
    time: "2026-03-31T14:00:00Z",
    indicator: "Conference Board Consumer Confidence",
    importance: "Medium",
    previous: "104.1",
    forecast: "103.5",
    actual: null,
    unit: "index",
    country: "USA",
    category: "Consumer",
    definitionEn: "The Conference Board Consumer Confidence Index surveys 3,000 US households on their views about current and future economic conditions, including business conditions, employment, and income.",
    definitionKo: "컨퍼런스보드 소비자신뢰지수는 3,000가구를 대상으로 기업 환경, 고용, 소득 등 현재 및 미래 경제 상황에 대한 인식을 조사합니다.",
    impactEn: "Moderate impact. Strong reading suggests consumers are willing to spend, supporting GDP. Weak reading warns of upcoming slowdown.",
    impactKo: "중간 정도의 영향. 강한 수치는 소비자들의 지출 의향을 나타내며 GDP를 지지합니다. 약한 수치는 향후 경기 둔화를 경고합니다.",
    correlationEn: "Leading indicator for Retail Sales. High consumer confidence → More retail spending → Revenue growth for Consumer Discretionary sector.",
    correlationKo: "소매 판매의 선행 지표입니다. 높은 소비자신뢰 → 소매 지출 증가 → 임의소비재 섹터 매출 성장.",
    counterIndicatorEn: "Retail Sales, Credit Card Delinquencies",
    counterIndicatorKo: "소매 판매, 신용카드 연체율"
  },

  // ===== APRIL 2026 =====
  {
    id: "2026-04-01-ism-mfg",
    time: "2026-04-01T14:00:00Z",
    indicator: "ISM Manufacturing PMI",
    importance: "High",
    previous: "51.2",
    forecast: "51.0",
    actual: null,
    unit: "index",
    country: "USA",
    category: "Manufacturing",
    definitionEn: "The ISM Manufacturing PMI (Purchasing Managers' Index) is a monthly indicator of economic activity in the US manufacturing sector. A reading above 50 indicates expansion.",
    definitionKo: "ISM 제조업 PMI(구매관리자지수)는 미국 제조업 부문의 월간 경제 활동 지표입니다. 50 이상이면 경기 확장을 나타냅니다.",
    impactEn: "High impact. A reading above 50 is bullish for equities and the USD. Below 50 signals contraction and is bearish.",
    impactKo: "큰 영향을 미칩니다. 50 이상이면 주식과 달러에 강세 신호. 50 미만은 수축을 나타내며 약세 신호입니다.",
    correlationEn: "Leading indicator for GDP. Strong ISM Mfg → Industrials and Materials stocks rally.",
    correlationKo: "GDP의 선행 지표입니다. 강한 ISM 제조업 → 산업재 및 소재 주식 상승.",
    counterIndicatorEn: "GDP Growth Rate, Factory Orders",
    counterIndicatorKo: "GDP 성장률, 공장주문"
  },
  {
    id: "2026-04-03-nfp",
    time: "2026-04-03T12:30:00Z",
    indicator: "Non-Farm Payrolls (NFP)",
    importance: "High",
    previous: "170K",
    forecast: "165K",
    actual: null,
    unit: "K",
    country: "USA",
    category: "Employment",
    definitionEn: "Non-Farm Payrolls measures the change in the number of employed people during the previous month, excluding the farming industry. Released on the first Friday of each month by the Bureau of Labor Statistics.",
    definitionKo: "비농업 고용지수는 농업을 제외한 지난 한 달 동안 고용된 인원수의 변화를 측정합니다. 매달 첫째 주 금요일에 노동통계국에서 발표합니다.",
    impactEn: "One of the most market-moving reports. Strong NFP = Economic strength, but may lead to rate hike fears. Weak NFP = Rate cut hopes.",
    impactKo: "시장에 가장 큰 영향을 미치는 지표 중 하나입니다. 강한 NFP = 경제적 강세, 하지만 금리 인상 우려로 이어질 수 있습니다. 약한 NFP = 금리 인하 기대감.",
    correlationEn: "Strong NFP → Strong USD → Weak Gold. Closely linked to Fed rate decisions.",
    correlationKo: "강한 NFP → 달러 강세 → 금 약세. 연준 금리 결정과 밀접하게 연결됩니다.",
    counterIndicatorEn: "Initial Jobless Claims, Fed Funds Rate",
    counterIndicatorKo: "신규 실업수당 청구 건수, 연방기금금리"
  },
  {
    id: "2026-04-03-unemp",
    time: "2026-04-03T12:30:00Z",
    indicator: "Unemployment Rate",
    importance: "High",
    previous: "4.0%",
    forecast: "4.0%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Employment",
    definitionEn: "The Unemployment Rate measures the percentage of the total work force that is unemployed and actively seeking employment.",
    definitionKo: "실업률은 총 노동력 중 실업 상태에 있으며 적극적으로 취업을 원하는 사람의 비율을 측정합니다.",
    impactEn: "Higher unemployment = Rate cut expectations = Bullish for Bonds.",
    impactKo: "높은 실업률 = 금리 인하 기대 = 채권에 강세.",
    correlationEn: "Inverse with NFP. Rising unemployment → Fed dovish pivot → Rate cuts.",
    correlationKo: "NFP와 반비례. 실업률 상승 → 연준 비둘기파 전환 → 금리 인하.",
    counterIndicatorEn: "Non-Farm Payrolls, JOLTS Job Openings",
    counterIndicatorKo: "비농업 고용지수, JOLTS 구인 건수"
  },
  {
    id: "2026-04-10-cpi",
    time: "2026-04-10T12:30:00Z",
    indicator: "Consumer Price Index (CPI) (MoM)",
    importance: "High",
    previous: "0.3%",
    forecast: "0.3%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Consumer Price Index measures the average change in prices paid by urban consumers for a basket of goods and services.",
    definitionKo: "소비자물가지수는 도시 소비자들이 구매하는 상품 및 서비스 바구니의 가격 평균 변화를 측정합니다.",
    impactEn: "Extremely high impact. Hot CPI → Rate hike fears. Cool CPI → Rate cut hopes.",
    impactKo: "매우 큰 영향을 미칩니다. 높은 CPI → 금리 인상 우려. 낮은 CPI → 금리 인하 기대.",
    correlationEn: "High CPI → Rate hike → Downward pressure on NASDAQ and growth stocks.",
    correlationKo: "높은 CPI → 금리 인상 → 나스닥과 성장주 하락 압력.",
    counterIndicatorEn: "Fed Funds Rate, Core PCE, NASDAQ",
    counterIndicatorKo: "연방기금금리, 근원 PCE, 나스닥"
  },
  {
    id: "2026-04-11-ppi",
    time: "2026-04-11T12:30:00Z",
    indicator: "Producer Price Index (PPI) (MoM)",
    importance: "Medium",
    previous: "0.3%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The PPI measures the average change in selling prices received by domestic producers. A leading indicator for consumer price inflation.",
    definitionKo: "생산자물가지수(PPI)는 국내 생산자가 받는 판매 가격의 평균 변화를 측정합니다. 소비자 물가 인플레이션의 선행 지표입니다.",
    impactEn: "Moderate impact. Rising PPI signals pipeline inflation pressure that eventually reaches consumers.",
    impactKo: "중간 정도의 영향. 상승하는 PPI는 결국 소비자에게 도달하는 공급망 인플레이션 압박을 나타냅니다.",
    correlationEn: "Leading indicator for CPI. PPI rise → Future CPI rise → Monetary tightening risk.",
    correlationKo: "CPI의 선행 지표입니다. PPI 상승 → 미래 CPI 상승 → 통화 긴축 위험.",
    counterIndicatorEn: "Consumer Price Index (CPI)",
    counterIndicatorKo: "소비자물가지수(CPI)"
  },
  {
    id: "2026-04-16-retail",
    time: "2026-04-16T12:30:00Z",
    indicator: "Retail Sales (MoM)",
    importance: "High",
    previous: "0.5%",
    forecast: "0.4%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Consumer",
    definitionEn: "Retail Sales measures total receipts at stores selling merchandise to final consumers. A primary gauge of consumer spending.",
    definitionKo: "소매 판매는 최종 소비자에게 상품을 판매하는 매장의 총 수입을 측정합니다. 소비자 지출의 주요 측정 지표입니다.",
    impactEn: "High impact. Strong data supports GDP growth and corporate earnings for retail and consumer discretionary stocks.",
    impactKo: "큰 영향을 미칩니다. 강한 데이터는 소매 및 소비재 주식의 GDP 성장과 기업 실적을 지지합니다.",
    correlationEn: "Strong retail → GDP up → Earnings up → Stocks rally (especially Consumer Discretionary ETFs like XLY).",
    correlationKo: "강한 소매 → GDP 상승 → 실적 상승 → 주식 랠리(특히 임의소비재 ETF XLY).",
    counterIndicatorEn: "Consumer Confidence Index, E-commerce Data",
    counterIndicatorKo: "소비자신뢰지수, 전자상거래 데이터"
  },
  {
    id: "2026-04-30-gdp",
    time: "2026-04-30T12:30:00Z",
    indicator: "GDP Growth Rate (Q1 2026 Advance)",
    importance: "High",
    previous: "2.3%",
    forecast: "2.1%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Growth",
    definitionEn: "The Advance GDP estimate is the first of three releases for a given quarter. It measures the monetary value of all goods and services produced within the US borders, adjusted for inflation.",
    definitionKo: "GDP 속보치는 특정 분기에 대한 세 번의 발표 중 첫 번째입니다. 인플레이션을 조정하여 미국 내에서 생산된 모든 상품 및 서비스의 화폐 가치를 측정합니다.",
    impactEn: "Very high impact. Strong GDP = Healthy economy = Positive for equities. Negative GDP = Recession risk = Flight to safety.",
    impactKo: "매우 큰 영향을 미칩니다. 강한 GDP = 건강한 경제 = 주식에 긍정적. 마이너스 GDP = 경기침체 위험 = 안전자산 선호.",
    correlationEn: "GDP confirms or refutes macro trends. Strong GDP + Low Inflation = Goldilocks scenario → Stocks bull market.",
    correlationKo: "GDP는 거시 경제 추세를 확인하거나 반박합니다. 강한 GDP + 낮은 인플레이션 = 골디락스 시나리오 → 주식 강세장.",
    counterIndicatorEn: "Unemployment Rate, Consumer Spending, Trade Balance",
    counterIndicatorKo: "실업률, 소비자 지출, 무역수지"
  },
  {
    id: "2026-04-30-pce",
    time: "2026-04-30T12:30:00Z",
    indicator: "Core PCE Price Index (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Fed's preferred inflation gauge, measuring price changes for goods and services excluding food and energy. Released by the Bureau of Economic Analysis.",
    definitionKo: "연준이 선호하는 인플레이션 지표로, 식품과 에너지를 제외한 상품 및 서비스의 가격 변동을 측정합니다. 경제분석국에서 발표합니다.",
    impactEn: "Directly sets Fed rate policy direction. The most important inflation print of the month.",
    impactKo: "연준 금리 정책 방향을 직접적으로 결정합니다. 한 달 중 가장 중요한 인플레이션 지표입니다.",
    correlationEn: "High PCE → Rates stay higher for longer → Growth stocks (especially NASDAQ) face headwinds.",
    correlationKo: "높은 PCE → 장기 높은 금리 유지 → 성장주(특히 나스닥) 역풍 직면.",
    counterIndicatorEn: "Fed Funds Rate, S&P 500 P/E Ratio",
    counterIndicatorKo: "연방기금금리, S&P 500 주가수익비율"
  },

  // ===== MAY 2026 =====
  {
    id: "2026-05-01-nfp",
    time: "2026-05-01T12:30:00Z",
    indicator: "Non-Farm Payrolls (NFP)",
    importance: "High",
    previous: "165K",
    forecast: "160K",
    actual: null,
    unit: "K",
    country: "USA",
    category: "Employment",
    definitionEn: "Non-Farm Payrolls measures the change in the number of employed people during the previous month, excluding the farming industry.",
    definitionKo: "비농업 고용지수는 농업을 제외한 지난 한 달 동안 고용된 인원수의 변화를 측정합니다.",
    impactEn: "One of the most market-moving reports. Strong NFP = Economic strength, but may lead to rate hike fears.",
    impactKo: "시장에 가장 큰 영향을 미치는 지표 중 하나입니다. 강한 NFP = 경제적 강세, 하지만 금리 인상 우려로 이어질 수 있습니다.",
    correlationEn: "Strong NFP → Strong USD → Weak Gold. High jobs = Inflation risk = Hawkish Fed.",
    correlationKo: "강한 NFP → 달러 강세 → 금 약세. 높은 고용 = 인플레이션 위험 = 매파적 연준.",
    counterIndicatorEn: "Initial Jobless Claims, Fed Funds Rate",
    counterIndicatorKo: "신규 실업수당 청구 건수, 연방기금금리"
  },
  {
    id: "2026-05-06-fomc-day1",
    time: "2026-05-06T14:00:00Z",
    indicator: "FOMC Meeting (Day 1)",
    importance: "High",
    previous: "4.25-4.50%",
    forecast: "4.25-4.50%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The FOMC meets to review economic and financial conditions and determine monetary policy, setting the target range for the federal funds rate.",
    definitionKo: "FOMC는 경제 및 금융 상황을 검토하고 연방기금금리 목표 범위를 설정하는 통화 정책을 결정하기 위해 모입니다.",
    impactEn: "Markets position ahead of the decision. Volatility typically increases in the days leading up to and following the meeting.",
    impactKo: "시장은 결정을 앞두고 포지셔닝합니다. 회의 전후 며칠 동안 변동성이 일반적으로 증가합니다.",
    correlationEn: "FOMC meetings create volatility. VIX typically rises before the decision and falls after.",
    correlationKo: "FOMC 회의는 변동성을 만듭니다. VIX는 일반적으로 결정 전에 상승하고 이후에 하락합니다.",
    counterIndicatorEn: "VIX, S&P 500, Fed Funds Futures",
    counterIndicatorKo: "VIX, S&P 500, 연방기금금리 선물"
  },
  {
    id: "2026-05-07-fomc-decision",
    time: "2026-05-07T18:00:00Z",
    indicator: "FOMC Rate Decision & Press Conference",
    importance: "High",
    previous: "4.25-4.50%",
    forecast: "4.25-4.50%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The FOMC announces its interest rate decision, statement, and the Fed Chair holds a press conference to explain the reasoning and outlook.",
    definitionKo: "FOMC가 금리 결정 및 성명을 발표하고 연준 의장이 이유와 전망을 설명하는 기자회견을 엽니다.",
    impactEn: "The most market-moving event. Tone, dot plot updates, and guidance can dramatically shift market direction.",
    impactKo: "시장에 가장 큰 영향을 미치는 이벤트입니다. 어조, 점도표 업데이트, 가이던스가 시장 방향을 극적으로 바꿀 수 있습니다.",
    correlationEn: "Rate Hold + Dovish tone → Rally in stocks. Rate Hold + Hawkish tone → Sell-off in growth stocks.",
    correlationKo: "금리 동결 + 비둘기파적 어조 → 주식 랠리. 금리 동결 + 매파적 어조 → 성장주 매도세.",
    counterIndicatorEn: "2-Year Treasury Yield, Dollar Index (DXY)",
    counterIndicatorKo: "2년 국채 수익률, 달러 인덱스(DXY)"
  },
  {
    id: "2026-05-13-cpi",
    time: "2026-05-13T12:30:00Z",
    indicator: "Consumer Price Index (CPI) (MoM)",
    importance: "High",
    previous: "0.3%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Consumer Price Index measures average price changes for a basket of goods and services purchased by consumers.",
    definitionKo: "소비자물가지수는 소비자가 구매하는 상품 및 서비스 바구니의 평균 가격 변화를 측정합니다.",
    impactEn: "Extremely high impact. The CPI print can single-handedly reverse market trends.",
    impactKo: "매우 큰 영향을 미칩니다. CPI 수치는 단독으로 시장 추세를 역전시킬 수 있습니다.",
    correlationEn: "Hot CPI → Bond yields spike → NASDAQ falls (discounted cash flows hurt by higher rates).",
    correlationKo: "높은 CPI → 채권 수익률 급등 → 나스닥 하락(높은 금리로 인한 할인 현금흐름 타격).",
    counterIndicatorEn: "10-Year Treasury Yield, Fed Dot Plot",
    counterIndicatorKo: "10년 국채 수익률, 연준 점도표"
  },
  {
    id: "2026-05-15-retail",
    time: "2026-05-15T12:30:00Z",
    indicator: "Retail Sales (MoM)",
    importance: "High",
    previous: "0.4%",
    forecast: "0.3%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Consumer",
    definitionEn: "Retail Sales measures the change in the total value of sales at the retail level. A key indicator of consumer spending health.",
    definitionKo: "소매 판매는 소매 수준에서의 총 판매 가치 변화를 측정합니다. 소비자 지출 건전성의 핵심 지표입니다.",
    impactEn: "Strong reading supports S&P 500 earnings expectations. Weak reading triggers recession fears.",
    impactKo: "강한 수치는 S&P 500 실적 기대를 지지합니다. 약한 수치는 경기침체 우려를 촉발합니다.",
    correlationEn: "Strong retail → Consumer stocks (XRT) rally → GDP estimates revised up → Lower risk of Fed cuts.",
    correlationKo: "강한 소매 → 소비자 주식(XRT) 상승 → GDP 전망 상향 조정 → 연준 금리 인하 위험 감소.",
    counterIndicatorEn: "Consumer Confidence, Savings Rate",
    counterIndicatorKo: "소비자신뢰지수, 저축률"
  },
  {
    id: "2026-05-30-pce",
    time: "2026-05-30T12:30:00Z",
    indicator: "Core PCE Price Index (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The Fed's preferred inflation measure. Core PCE directly feeds into the FOMC's rate decisions.",
    definitionKo: "연준이 선호하는 인플레이션 측정 지표입니다. 근원 PCE는 FOMC의 금리 결정에 직접적으로 반영됩니다.",
    impactEn: "Critical for June FOMC meeting preparation. Deviation from 2% target influences rate path.",
    impactKo: "6월 FOMC 회의 준비에 매우 중요합니다. 2% 목표에서의 이탈이 금리 경로에 영향을 미칩니다.",
    correlationEn: "Persistently high Core PCE → Fed delays rate cuts → Dollar strength → Emerging market weakness.",
    correlationKo: "지속적으로 높은 근원 PCE → 연준 금리 인하 지연 → 달러 강세 → 신흥 시장 약세.",
    counterIndicatorEn: "Emerging Market ETFs, Dollar Index",
    counterIndicatorKo: "신흥시장 ETF, 달러 인덱스"
  },

  // ===== JUNE 2026 =====
  {
    id: "2026-06-05-nfp",
    time: "2026-06-05T12:30:00Z",
    indicator: "Non-Farm Payrolls (NFP)",
    importance: "High",
    previous: "160K",
    forecast: "155K",
    actual: null,
    unit: "K",
    country: "USA",
    category: "Employment",
    definitionEn: "Non-Farm Payrolls measures the monthly change in employment excluding agriculture. The most widely anticipated US economic indicator.",
    definitionKo: "비농업 고용지수는 농업을 제외한 월간 고용 변화를 측정합니다. 가장 널리 예상되는 미국 경제 지표입니다.",
    impactEn: "Directional catalyst for all asset classes. Miss → Rate cut bets increase → Bond rally.",
    impactKo: "모든 자산 클래스의 방향성 촉매제입니다. 부진 → 금리 인하 베팅 증가 → 채권 상승.",
    correlationEn: "Strong NFP → Stocks initially positive, then rate fear → Rotation from Growth to Value.",
    correlationKo: "강한 NFP → 주식 초기 긍정적, 이후 금리 우려 → 성장주에서 가치주로 로테이션.",
    counterIndicatorEn: "JOLTS Job Openings, Average Hourly Earnings",
    counterIndicatorKo: "JOLTS 구인 건수, 평균 시간당 임금"
  },
  {
    id: "2026-06-11-cpi",
    time: "2026-06-11T12:30:00Z",
    indicator: "Consumer Price Index (CPI) (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "Monthly measure of consumer price changes. Twelve-month trend determines if the Fed is winning or losing the inflation battle.",
    definitionKo: "소비자 물가 변화의 월간 측정치입니다. 12개월 추세는 연준이 인플레이션 전투에서 이기고 있는지 지고 있는지를 결정합니다.",
    impactEn: "Pre-FOMC CPI release is crucial. A surprise can shift rate expectations before the June meeting.",
    impactKo: "FOMC 이전 CPI 발표가 매우 중요합니다. 서프라이즈가 6월 회의 전에 금리 기대를 바꿀 수 있습니다.",
    correlationEn: "CPI below 2.5% YoY → Strong case for rate cut in June FOMC → Risk-on rally.",
    correlationKo: "CPI 전년 대비 2.5% 미만 → 6월 FOMC 금리 인하 강력 근거 → 위험 선호 랠리.",
    counterIndicatorEn: "Fed Funds Futures, S&P 500",
    counterIndicatorKo: "연방기금금리 선물, S&P 500"
  },
  {
    id: "2026-06-17-fomc-day1",
    time: "2026-06-17T14:00:00Z",
    indicator: "FOMC Meeting (Day 1)",
    importance: "High",
    previous: "4.25-4.50%",
    forecast: "4.00-4.25%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The FOMC's June meeting includes updated Summary of Economic Projections (SEP) and the dot plot, making it a particularly significant meeting for market guidance.",
    definitionKo: "FOMC 6월 회의에는 최신 경제 전망 요약(SEP)과 점도표가 포함되어 있어 시장 가이던스에 있어 특히 중요한 회의입니다.",
    impactEn: "High anticipation given updated dot plot projections. Markets price in one rate cut with 60% probability.",
    impactKo: "최신 점도표 전망으로 기대감이 높습니다. 시장은 60% 확률로 한 번의 금리 인하를 반영합니다.",
    correlationEn: "Dot plot shift dovish → Bond yields fall → Tech and Growth stocks rally.",
    correlationKo: "점도표 비둘기파적 전환 → 채권 수익률 하락 → 기술주 및 성장주 상승.",
    counterIndicatorEn: "2Y Treasury, CME FedWatch Probabilities",
    counterIndicatorKo: "2년 국채, CME 페드워치 확률"
  },
  {
    id: "2026-06-18-fomc-decision",
    time: "2026-06-18T18:00:00Z",
    indicator: "FOMC Rate Decision & Press Conference",
    importance: "High",
    previous: "4.25-4.50%",
    forecast: "4.00-4.25%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The June FOMC decision includes an updated dot plot and quarterly economic projections. The most anticipated FOMC of the year after the March meeting.",
    definitionKo: "6월 FOMC 결정에는 최신 점도표와 분기별 경제 전망이 포함됩니다. 3월 회의 다음으로 연중 가장 기대되는 FOMC입니다.",
    impactEn: "Rate cut scenario: Stocks rally, Bonds rally, USD weakens, Gold rises. Rate hold with hawkish tone: Opposite.",
    impactKo: "금리 인하 시나리오: 주식 상승, 채권 상승, 달러 약세, 금 상승. 매파적 어조의 금리 동결: 반대.",
    correlationEn: "First rate cut → Historical bullish signal for Stocks over 12 months. Short-term volatility expected.",
    correlationKo: "첫 번째 금리 인하 → 12개월에 걸쳐 주식에 역사적 강세 신호. 단기 변동성 예상.",
    counterIndicatorEn: "VIX, Gold, USD Index, 10Y Treasury",
    counterIndicatorKo: "VIX, 금, 달러 인덱스, 10년 국채"
  },
  {
    id: "2026-06-19-retail",
    time: "2026-06-19T12:30:00Z",
    indicator: "Retail Sales (MoM)",
    importance: "Medium",
    previous: "0.3%",
    forecast: "0.3%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Consumer",
    definitionEn: "Monthly measure of consumer spending at the retail level. Covers all types of retail stores, food services, and gas stations.",
    definitionKo: "소매 수준에서의 소비자 지출 월간 측정치입니다. 모든 유형의 소매점, 식음료 서비스, 주유소를 포괄합니다.",
    impactEn: "Moderate impact in June given FOMC dominates. Still important for consumer health assessment.",
    impactKo: "6월에는 FOMC가 지배적이어서 중간 정도의 영향. 그래도 소비자 건전성 평가에 중요합니다.",
    correlationEn: "Post-FOMC retail data confirms or denies economic soft/hard landing narrative.",
    correlationKo: "FOMC 이후 소매 데이터는 경제의 연착륙/경착륙 내러티브를 확인하거나 부정합니다.",
    counterIndicatorEn: "Consumer Confidence, University of Michigan Sentiment",
    counterIndicatorKo: "소비자신뢰지수, 미시간대 소비자심리지수"
  },
  {
    id: "2026-06-27-pce",
    time: "2026-06-27T12:30:00Z",
    indicator: "Core PCE Price Index (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The monthly Core PCE release following a rate decision is critical for confirming whether the Fed made the right call.",
    definitionKo: "금리 결정 이후 발표되는 월간 근원 PCE는 연준이 올바른 결정을 내렸는지 확인하는 데 매우 중요합니다.",
    impactEn: "Post-FOMC PCE validates or challenges the rate decision narrative. Surprise can cause sharp reversal.",
    impactKo: "FOMC 이후 PCE는 금리 결정 내러티브를 검증하거나 도전합니다. 서프라이즈는 급격한 반전을 일으킬 수 있습니다.",
    correlationEn: "If cut + PCE still high → Market questions Fed credibility → Volatility spike. If cut + PCE falling → Goldilocks confirmed.",
    correlationKo: "금리 인하 + 여전히 높은 PCE → 시장이 연준 신뢰성 의문 → 변동성 급등. 금리 인하 + PCE 하락 → 골디락스 확인.",
    counterIndicatorEn: "VIX, Long-term Treasury ETFs (TLT)",
    counterIndicatorKo: "VIX, 장기 국채 ETF(TLT)"
  },

  // ===== JULY 2026 =====
  {
    id: "2026-07-03-nfp",
    time: "2026-07-03T12:30:00Z",
    indicator: "Non-Farm Payrolls (NFP)",
    importance: "High",
    previous: "155K",
    forecast: "158K",
    actual: null,
    unit: "K",
    country: "USA",
    category: "Employment",
    definitionEn: "Monthly employment report. July NFP is particularly important as it frames the economic narrative heading into H2 2026.",
    definitionKo: "월간 고용 보고서입니다. 7월 NFP는 2026년 하반기로 향하는 경제 내러티브를 형성하는 데 특히 중요합니다.",
    impactEn: "Strong summer jobs data supports consumer spending thesis for Q3. A miss would fuel recession fears.",
    impactKo: "강한 여름 고용 데이터는 3분기 소비자 지출 논거를 지지합니다. 부진하면 경기침체 우려를 부추길 것입니다.",
    correlationEn: "July NFP feeds into July FOMC outlook. Strong NFP reduces probability of July rate cut.",
    correlationKo: "7월 NFP는 7월 FOMC 전망에 반영됩니다. 강한 NFP는 7월 금리 인하 가능성을 줄입니다.",
    counterIndicatorEn: "Fed Funds Futures, ISM Services",
    counterIndicatorKo: "연방기금금리 선물, ISM 서비스"
  },
  {
    id: "2026-07-15-cpi",
    time: "2026-07-15T12:30:00Z",
    indicator: "Consumer Price Index (CPI) (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The July CPI print is important context for the late July FOMC meeting. Provides the latest read on whether inflation is sustainably declining.",
    definitionKo: "7월 CPI 수치는 7월 말 FOMC 회의의 중요한 맥락을 제공합니다. 인플레이션이 지속 가능하게 하락하고 있는지 최신 정보를 제공합니다.",
    impactEn: "Pre-FOMC CPI reading. A miss to the upside could derail rate cut expectations for July.",
    impactKo: "FOMC 이전 CPI 수치. 상방 서프라이즈는 7월 금리 인하 기대를 무산시킬 수 있습니다.",
    correlationEn: "CPI consistent with target → Rate cut probability spikes → USD weakens → Gold, EM stocks rally.",
    correlationKo: "목표치에 부합하는 CPI → 금리 인하 확률 급등 → 달러 약세 → 금, 신흥시장 주식 상승.",
    counterIndicatorEn: "Gold, Emerging Market ETFs, USD Index",
    counterIndicatorKo: "금, 신흥시장 ETF, 달러 인덱스"
  },
  {
    id: "2026-07-17-retail",
    time: "2026-07-17T12:30:00Z",
    indicator: "Retail Sales (MoM)",
    importance: "Medium",
    previous: "0.3%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Consumer",
    definitionEn: "July Retail Sales data shows summer spending trends, capturing back-to-school shopping and seasonal consumer patterns.",
    definitionKo: "7월 소매 판매 데이터는 여름 지출 동향을 보여주며, 개학 쇼핑 및 계절적 소비자 패턴을 포착합니다.",
    impactEn: "Summer consumer spending check. Strong reading supports Q3 earnings estimates for retail stocks.",
    impactKo: "여름 소비자 지출 점검. 강한 수치는 소매 주식의 3분기 실적 전망을 지지합니다.",
    correlationEn: "Strong retail + cooling inflation = Best scenario for stocks (Goldilocks). Weak retail + high inflation = Stagflation risk.",
    correlationKo: "강한 소매 + 냉각되는 인플레이션 = 주식에 최고의 시나리오(골디락스). 약한 소매 + 높은 인플레이션 = 스태그플레이션 위험.",
    counterIndicatorEn: "GDP Q2 Advance, Consumer Credit Data",
    counterIndicatorKo: "GDP Q2 속보치, 소비자 신용 데이터"
  },
  {
    id: "2026-07-29-fomc-day1",
    time: "2026-07-29T14:00:00Z",
    indicator: "FOMC Meeting (Day 1)",
    importance: "High",
    previous: "4.00-4.25%",
    forecast: "3.75-4.00%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The July FOMC meeting, where the committee will decide on the pace of monetary easing given the economic data accumulated since June.",
    definitionKo: "7월 FOMC 회의로, 위원회는 6월 이후 축적된 경제 데이터를 바탕으로 통화 완화 속도를 결정합니다.",
    impactEn: "Second rate cut decision in sight. Markets pricing in 65% probability of 25bps cut.",
    impactKo: "두 번째 금리 인하 결정이 눈앞에 있습니다. 시장은 25bp 인하 가능성을 65%로 반영합니다.",
    correlationEn: "Second consecutive cut → Confirms easing cycle → Multi-month rally in Bonds and Growth stocks.",
    correlationKo: "연속 두 번째 금리 인하 → 완화 사이클 확인 → 채권 및 성장주의 수개월 랠리.",
    counterIndicatorEn: "Fed Dot Plot, 10Y Treasury, Nasdaq",
    counterIndicatorKo: "연준 점도표, 10년 국채, 나스닥"
  },
  {
    id: "2026-07-30-fomc-decision",
    time: "2026-07-30T18:00:00Z",
    indicator: "FOMC Rate Decision & Press Conference",
    importance: "High",
    previous: "4.00-4.25%",
    forecast: "3.75-4.00%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Central Bank",
    definitionEn: "The July FOMC rate decision. The press conference will focus on the pace of future cuts and whether the easing cycle is accelerating.",
    definitionKo: "7월 FOMC 금리 결정. 기자회견은 미래 금리 인하 속도와 완화 사이클 가속 여부에 초점을 맞출 것입니다.",
    impactEn: "Rate cut + Dovish press conference → Strong risk-on: Stocks, Crypto, EM assets all rally.",
    impactKo: "금리 인하 + 비둘기파적 기자회견 → 강력한 위험 선호: 주식, 암호화폐, 신흥시장 자산 모두 상승.",
    correlationEn: "Easing cycle acceleration → Small-cap stocks outperform (rate-sensitive) → Russell 2000 rally.",
    correlationKo: "완화 사이클 가속 → 소형주 아웃퍼폼(금리 민감) → 러셀 2000 상승.",
    counterIndicatorEn: "Russell 2000, High Yield Bond Spreads",
    counterIndicatorKo: "러셀 2000, 하이일드 채권 스프레드"
  },
  {
    id: "2026-07-31-gdp-q2",
    time: "2026-07-31T12:30:00Z",
    indicator: "GDP Growth Rate (Q2 2026 Advance)",
    importance: "High",
    previous: "2.1%",
    forecast: "2.0%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Growth",
    definitionEn: "The Advance GDP estimate for Q2 2026. This first reading of the quarter's economic output sets expectations for corporate earnings revisions and monetary policy trajectory.",
    definitionKo: "2026년 2분기 GDP 속보치입니다. 분기 경제 생산량의 첫 번째 수치로, 기업 실적 수정과 통화 정책 방향에 대한 기대를 설정합니다.",
    impactEn: "Strong GDP confirms soft landing. Weak GDP fuels stagflation or hard landing debate.",
    impactKo: "강한 GDP는 연착륙을 확인합니다. 약한 GDP는 스태그플레이션 또는 경착륙 논쟁을 부추깁니다.",
    correlationEn: "Weak GDP + Low Inflation = Rate cut acceleration. Strong GDP + Low Inflation = Goldilocks continuation.",
    correlationKo: "약한 GDP + 낮은 인플레이션 = 금리 인하 가속. 강한 GDP + 낮은 인플레이션 = 골디락스 지속.",
    counterIndicatorEn: "Corporate Earnings, S&P 500 Forward P/E",
    counterIndicatorKo: "기업 실적, S&P 500 선행 주가수익비율"
  },

  // ===== AUGUST 2026 =====
  {
    id: "2026-08-07-nfp",
    time: "2026-08-07T12:30:00Z",
    indicator: "Non-Farm Payrolls (NFP)",
    importance: "High",
    previous: "158K",
    forecast: "155K",
    actual: null,
    unit: "K",
    country: "USA",
    category: "Employment",
    definitionEn: "August NFP provides the latest employment snapshot heading into the September FOMC decision, one of the most important meetings of the year.",
    definitionKo: "8월 NFP는 연중 가장 중요한 회의 중 하나인 9월 FOMC 결정을 앞두고 최신 고용 스냅샷을 제공합니다.",
    impactEn: "Critical for September FOMC. Weak NFP → September rate cut priced in. Strong NFP → Fed may pause.",
    impactKo: "9월 FOMC에 매우 중요합니다. 약한 NFP → 9월 금리 인하 반영. 강한 NFP → 연준이 일시 중단할 수 있습니다.",
    correlationEn: "August NFP sets the tone for Q4 market outlook and September rate cut probability.",
    correlationKo: "8월 NFP는 4분기 시장 전망과 9월 금리 인하 확률에 대한 분위기를 설정합니다.",
    counterIndicatorEn: "JOLTS, Initial Claims, September FOMC Probability",
    counterIndicatorKo: "JOLTS, 신규 청구 건수, 9월 FOMC 확률"
  },
  {
    id: "2026-08-12-cpi",
    time: "2026-08-12T12:30:00Z",
    indicator: "Consumer Price Index (CPI) (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The August CPI is crucial context for Jackson Hole (Fed symposium) and September FOMC. It will confirm or challenge the disinflation narrative.",
    definitionKo: "8월 CPI는 잭슨홀(연준 심포지엄)과 9월 FOMC의 중요한 맥락입니다. 디스인플레이션 내러티브를 확인하거나 도전할 것입니다.",
    impactEn: "August CPI + Jackson Hole = Major market-moving combination. Inflation data frames the Fed Chair's speech.",
    impactKo: "8월 CPI + 잭슨홀 = 주요 시장 움직임 조합. 인플레이션 데이터가 연준 의장의 연설 틀을 잡습니다.",
    correlationEn: "Cool August CPI → Jackson Hole dovish signal → September rate cut priced at 80%+ → Rally.",
    correlationKo: "낮은 8월 CPI → 잭슨홀 비둘기파적 신호 → 9월 금리 인하 80%+ 반영 → 상승.",
    counterIndicatorEn: "Jackson Hole Speech Tone, Fed Funds Futures",
    counterIndicatorKo: "잭슨홀 연설 어조, 연방기금금리 선물"
  },
  {
    id: "2026-08-14-retail",
    time: "2026-08-14T12:30:00Z",
    indicator: "Retail Sales (MoM)",
    importance: "Medium",
    previous: "0.2%",
    forecast: "0.3%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Consumer",
    definitionEn: "August Retail Sales includes back-to-school spending boost. A key read on consumer health before the holiday season ramp-up begins.",
    definitionKo: "8월 소매 판매는 개학 지출 증가를 포함합니다. 휴일 시즌 증가가 시작되기 전 소비자 건강에 대한 핵심 정보입니다.",
    impactEn: "Back-to-school boost expected. Strong reading supports consumer discretionary sector heading into fall.",
    impactKo: "개학 특수가 예상됩니다. 강한 수치는 가을을 앞두고 임의소비재 섹터를 지지합니다.",
    correlationEn: "Strong August retail → Higher Q3 GDP estimates → Less urgency for rate cuts → Mild hawkish push.",
    correlationKo: "강한 8월 소매 → 높은 3분기 GDP 전망 → 금리 인하 긴급성 감소 → 약한 매파적 압박.",
    counterIndicatorEn: "Consumer Confidence, Holiday Sales Forecasts",
    counterIndicatorKo: "소비자신뢰지수, 연말 판매 전망"
  },
  {
    id: "2026-08-28-pce",
    time: "2026-08-28T12:30:00Z",
    indicator: "Core PCE Price Index (MoM)",
    importance: "High",
    previous: "0.2%",
    forecast: "0.2%",
    actual: null,
    unit: "%",
    country: "USA",
    category: "Inflation",
    definitionEn: "The August Core PCE is the last major inflation reading before the September FOMC. A critical data point for confirming or denying the September rate cut.",
    definitionKo: "8월 근원 PCE는 9월 FOMC 이전 마지막 주요 인플레이션 수치입니다. 9월 금리 인하를 확인하거나 부정하는 핵심 데이터 포인트입니다.",
    impactEn: "This print could finalize September rate cut expectations. Market is highly sensitive to any surprise.",
    impactKo: "이 수치가 9월 금리 인하 기대를 확정할 수 있습니다. 시장은 어떤 서프라이즈에도 매우 민감합니다.",
    correlationEn: "On-target PCE → September cut confirmed → Bond prices rally, yields fall, Growth stocks rise.",
    correlationKo: "목표치 부합 PCE → 9월 금리 인하 확정 → 채권 가격 상승, 수익률 하락, 성장주 상승.",
    counterIndicatorEn: "September FOMC Probability, NASDAQ, TLT",
    counterIndicatorKo: "9월 FOMC 확률, 나스닥, TLT"
  },

  // ===== KR / JP / EU EVENTS — MARCH 2026 =====
  {
    id: "2026-03-05-ecb-decision",
    time: "2026-03-05T13:15:00Z",
    indicator: "ECB Interest Rate Decision",
    indicatorKo: "유럽중앙은행(ECB) 기준금리 결정",
    importance: "High",
    previous: "2.75%",
    forecast: "2.50%",
    actual: null,
    unit: "%",
    country: "EU",
    category: "Central Bank",
    definitionEn: "The European Central Bank Governing Council sets the key interest rates for the eurozone. Decisions are taken 8 times per year and directly affect borrowing costs across 20 EU member states.",
    definitionKo: "유럽중앙은행(ECB) 이사회는 유로존 기준금리를 결정합니다. 연 8회 결정이 내려지며, 유로존 20개국 전반의 차입 비용에 직접 영향을 미칩니다.",
    impactEn: "ECB rate cuts weaken the Euro but boost European equities (DAX, CAC40). Rate hikes strengthen EUR and pressure European bonds.",
    impactKo: "ECB 금리 인하는 유로화를 약세로 만들지만 유럽 주식(DAX, CAC40)을 지지합니다. 금리 인상은 유로화를 강세로 만들고 유럽 채권에 압박을 줍니다.",
    correlationEn: "ECB cut → EUR weakens → Euro export stocks benefit → DAX rallies. Also lowers global risk-free rate.",
    correlationKo: "ECB 금리 인하 → 유로화 약세 → 유럽 수출 주식 혜택 → DAX 상승. 글로벌 무위험 금리도 낮아집니다.",
    counterIndicatorEn: "EUR/USD, DAX Index, Eurozone Bond Yields",
    counterIndicatorKo: "유로/달러 환율, DAX 지수, 유로존 국채 수익률"
  },
  {
    id: "2026-03-13-bok-decision",
    time: "2026-03-13T01:00:00Z",
    indicator: "Bank of Korea Rate Decision",
    indicatorKo: "한국은행(BOK) 기준금리 결정",
    importance: "High",
    previous: "2.75%",
    forecast: "2.50%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Central Bank",
    definitionEn: "The Bank of Korea Monetary Policy Committee meets 8 times per year to set the benchmark interest rate (Base Rate). Decisions impact Korean won, KOSPI, and domestic bond markets.",
    definitionKo: "한국은행 금융통화위원회는 연 8회 기준금리를 결정합니다. 결정은 원화 환율, 코스피 지수, 국내 채권 시장에 영향을 미칩니다.",
    impactEn: "Rate cut signals economic concern but supports Korean equities. Key for Korean won (KRW) direction and domestic lending rates.",
    impactKo: "금리 인하는 경기 우려를 시사하지만 국내 주식을 지지합니다. 원화 방향과 국내 대출금리에 핵심 지표입니다.",
    correlationEn: "BOK cut → KRW weakens → KOSPI export stocks gain (Samsung, Hyundai) → Korean bond prices rise.",
    correlationKo: "한국은행 금리 인하 → 원화 약세 → 코스피 수출주 상승(삼성, 현대) → 국내 채권 가격 상승.",
    counterIndicatorEn: "USD/KRW, KOSPI, Korean 3Y Treasury",
    counterIndicatorKo: "달러/원 환율, 코스피, 국고채 3년"
  },
  {
    id: "2026-03-17-japan-cpi",
    time: "2026-03-16T23:30:00Z",
    indicator: "Japan CPI (YoY)",
    indicatorKo: "일본 소비자물가지수 (전년비)",
    importance: "High",
    previous: "3.6%",
    forecast: "3.5%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Inflation",
    definitionEn: "Japan's Consumer Price Index measures the average change in prices paid by households for a basket of goods and services. Japan's decades-long battle with deflation makes any CPI rise historically significant.",
    definitionKo: "일본 소비자물가지수는 가계가 구매하는 상품 및 서비스 바구니의 가격 평균 변화를 측정합니다. 수십 년간의 디플레이션 역사로 인해 CPI 상승은 역사적으로 중요한 의미를 갖습니다.",
    impactEn: "Sustained inflation gives BOJ justification to raise rates further. Higher CPI → JPY strengthens → Export stocks (Toyota, Sony) fall.",
    impactKo: "지속적인 인플레이션은 일본은행(BOJ)의 추가 금리 인상 근거를 제공합니다. 높은 CPI → 엔화 강세 → 수출주(도요타, 소니) 하락.",
    correlationEn: "Japan CPI above 2% → BOJ rate hike expectation → JPY rally → Yen carry trade unwind → Global risk-off.",
    correlationKo: "일본 CPI 2% 초과 → BOJ 금리 인상 기대 → 엔화 강세 → 엔 캐리트레이드 청산 → 글로벌 위험 회피.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, BOJ Policy Rate",
    counterIndicatorKo: "달러/엔 환율, 닛케이225, BOJ 정책금리"
  },
  {
    id: "2026-03-26-korea-cpi",
    time: "2026-03-25T23:00:00Z",
    indicator: "Korea CPI (YoY)",
    indicatorKo: "한국 소비자물가지수 (전년비)",
    importance: "Medium",
    previous: "2.2%",
    forecast: "2.1%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Inflation",
    definitionEn: "Korea's CPI tracks price changes for a fixed basket of goods and services consumed by urban households. Published by Statistics Korea (KOSTAT) monthly.",
    definitionKo: "한국 CPI는 도시 가계가 소비하는 고정된 상품 및 서비스 바구니의 가격 변화를 추적합니다. 통계청에서 매월 발표합니다.",
    impactEn: "Affects BOK rate decisions. CPI near 2% target supports rate cut narrative. High CPI delays cuts and pressures Korean bonds.",
    impactKo: "한국은행 금리 결정에 영향을 미칩니다. CPI가 2% 목표에 근접하면 금리 인하 논거를 지지합니다. 높은 CPI는 인하를 지연시키고 국채에 압박을 줍니다.",
    correlationEn: "Low Korea CPI → BOK cut probable → KOSPI rally → KRW mild weakening.",
    correlationKo: "낮은 한국 CPI → 한국은행 금리 인하 가능 → 코스피 상승 → 원화 소폭 약세.",
    counterIndicatorEn: "BOK Base Rate, USD/KRW, KOSPI",
    counterIndicatorKo: "한국은행 기준금리, 달러/원 환율, 코스피"
  },

  // ===== KR / JP / EU EVENTS — APRIL 2026 =====
  {
    id: "2026-04-10-ecb-decision",
    time: "2026-04-10T13:15:00Z",
    indicator: "ECB Interest Rate Decision",
    indicatorKo: "유럽중앙은행(ECB) 기준금리 결정",
    importance: "High",
    previous: "2.50%",
    forecast: "2.25%",
    actual: null,
    unit: "%",
    country: "EU",
    category: "Central Bank",
    definitionEn: "The ECB Governing Council announces interest rate decisions. April meeting is closely watched as it follows Q1 GDP and inflation data, informing the pace of easing.",
    definitionKo: "ECB 이사회가 금리 결정을 발표합니다. 4월 회의는 1분기 GDP 및 인플레이션 데이터를 반영한 완화 속도를 가늠하는 중요 시점입니다.",
    impactEn: "Consecutive ECB cuts signal determined easing → European stocks rally, EUR weakens, peripheral bonds tighten.",
    impactKo: "연속적인 ECB 금리 인하는 완화 의지를 시사 → 유럽 주식 상승, 유로화 약세, 주변국 채권 스프레드 축소.",
    correlationEn: "ECB cut → EUR/USD falls → German exporters (BASF, Siemens) benefit → DAX outperforms.",
    correlationKo: "ECB 금리 인하 → 유로/달러 하락 → 독일 수출기업(BASF, 지멘스) 수혜 → DAX 아웃퍼폼.",
    counterIndicatorEn: "EUR/USD, DAX, Eurozone Inflation Swap",
    counterIndicatorKo: "유로/달러, DAX, 유로존 인플레이션 스왑"
  },
  {
    id: "2026-04-22-boj-decision",
    time: "2026-04-22T03:00:00Z",
    indicator: "Bank of Japan Policy Rate Decision",
    indicatorKo: "일본은행(BOJ) 정책금리 결정",
    importance: "High",
    previous: "0.50%",
    forecast: "0.50%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Central Bank",
    definitionEn: "The Bank of Japan Policy Board sets the uncollateralized overnight call rate. After decades of ultra-loose policy, the BOJ's normalization path is now a major global market driver.",
    definitionKo: "일본은행 정책위원회는 무담보 콜금리를 결정합니다. 수십 년간의 초완화 정책 이후, BOJ의 정상화 경로는 이제 글로벌 시장의 주요 동인이 되었습니다.",
    impactEn: "BOJ rate hike → JPY surges → Nikkei falls (exporters hurt) → Yen carry trade collapses → Global risk-off.",
    impactKo: "BOJ 금리 인상 → 엔화 급등 → 닛케이 하락(수출기업 타격) → 엔 캐리트레이드 붕괴 → 글로벌 위험 회피.",
    correlationEn: "Hawkish BOJ → USD/JPY drops sharply → Nikkei sells off → EM currencies under pressure from unwound yen carry.",
    correlationKo: "매파적 BOJ → 달러/엔 급락 → 닛케이 매도세 → 엔 캐리 청산에 따른 신흥국 통화 압박.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, Yen Carry Trade Basket",
    counterIndicatorKo: "달러/엔, 닛케이225, 엔 캐리트레이드 바스켓"
  },
  {
    id: "2026-04-16-japan-cpi",
    time: "2026-04-15T23:30:00Z",
    indicator: "Japan CPI (YoY)",
    indicatorKo: "일본 소비자물가지수 (전년비)",
    importance: "High",
    previous: "3.5%",
    forecast: "3.4%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Inflation",
    definitionEn: "Japan's monthly CPI released by Statistics Bureau. Critically watched ahead of BOJ policy meetings to assess whether inflation is sustainable or transitory.",
    definitionKo: "일본 통계국에서 발표하는 월간 CPI입니다. BOJ 정책 회의를 앞두고 인플레이션이 지속적인지 일시적인지 평가하기 위해 면밀히 주목받습니다.",
    impactEn: "Above-2% Japan CPI keeps rate hike pressure on BOJ. High CPI → JPY strengthens → Global carry trade risk.",
    impactKo: "2% 초과 일본 CPI는 BOJ에 금리 인상 압박을 유지합니다. 높은 CPI → 엔화 강세 → 글로벌 캐리트레이드 위험.",
    correlationEn: "Japan CPI surprise → Yen jumps → Korean won follows → KOSPI and Nikkei both pressured.",
    correlationKo: "일본 CPI 서프라이즈 → 엔화 급등 → 원화 동반 강세 → 코스피·닛케이 모두 압박.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, KOSPI",
    counterIndicatorKo: "달러/엔, 닛케이225, 코스피"
  },
  {
    id: "2026-04-28-bok-decision",
    time: "2026-04-28T01:00:00Z",
    indicator: "Bank of Korea Rate Decision",
    indicatorKo: "한국은행(BOK) 기준금리 결정",
    importance: "High",
    previous: "2.50%",
    forecast: "2.25%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Central Bank",
    definitionEn: "Bank of Korea Monetary Policy Committee rate decision. Following global central bank easing, the BOK assesses domestic inflation and growth for its rate path.",
    definitionKo: "한국은행 금융통화위원회 기준금리 결정입니다. 글로벌 중앙은행 완화 흐름에 따라 BOK는 국내 물가와 성장을 평가하여 금리 방향을 결정합니다.",
    impactEn: "Potential second cut of cycle. Further easing supports domestic lending, KOSPI, and housing market recovery.",
    impactKo: "사이클 내 두 번째 인하 가능성. 추가 완화는 국내 대출, 코스피, 부동산 시장 회복을 지지합니다.",
    correlationEn: "BOK sequential cuts → Domestic rate-sensitive stocks (REITs, financials) rally → Housing sector recovers.",
    correlationKo: "한국은행 연속 금리 인하 → 금리 민감 국내주(리츠, 금융주) 상승 → 부동산 섹터 회복.",
    counterIndicatorEn: "Korea Housing Price Index, KOSPI Financials",
    counterIndicatorKo: "한국 주택가격지수, 코스피 금융주"
  },

  // ===== KR / JP / EU EVENTS — MAY 2026 =====
  {
    id: "2026-05-22-japan-cpi",
    time: "2026-05-21T23:30:00Z",
    indicator: "Japan CPI (YoY)",
    indicatorKo: "일본 소비자물가지수 (전년비)",
    importance: "High",
    previous: "3.4%",
    forecast: "3.3%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Inflation",
    definitionEn: "Japan's CPI for April, released in May. Tracks price trends across food, energy, services, and goods categories. Key input for BOJ's summer policy review.",
    definitionKo: "5월에 발표되는 4월 일본 CPI입니다. 식품, 에너지, 서비스, 상품 카테고리의 물가 추세를 추적합니다. BOJ 하반기 정책 검토의 핵심 자료입니다.",
    impactEn: "May CPI pre-BOJ June meeting. Sustained above-2% → Markets price in June rate hike → JPY strength risk.",
    impactKo: "6월 BOJ 회의 이전 5월 CPI. 지속적 2% 초과 → 시장이 6월 금리 인상 반영 → 엔화 강세 위험.",
    correlationEn: "Japan CPI trend determines BOJ's H2 rate path → Global risk appetite impact through yen dynamics.",
    correlationKo: "일본 CPI 추세는 BOJ 하반기 금리 경로를 결정 → 엔화 역학을 통한 글로벌 위험 선호에 영향.",
    counterIndicatorEn: "BOJ Rate Decision, USD/JPY, S&P 500",
    counterIndicatorKo: "BOJ 금리 결정, 달러/엔, S&P 500"
  },
  {
    id: "2026-05-26-bok-decision",
    time: "2026-05-26T01:00:00Z",
    indicator: "Bank of Korea Rate Decision",
    indicatorKo: "한국은행(BOK) 기준금리 결정",
    importance: "Medium",
    previous: "2.25%",
    forecast: "2.25%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Central Bank",
    definitionEn: "Bank of Korea policy meeting. With rates already reduced, the May meeting evaluates whether further cuts are warranted given global conditions and domestic growth.",
    definitionKo: "한국은행 정책 회의입니다. 이미 금리를 인하한 상황에서, 5월 회의는 글로벌 환경과 국내 성장을 고려해 추가 인하 여부를 검토합니다.",
    impactEn: "Hold expected. Forward guidance on further cuts key for Korean bond and FX markets.",
    impactKo: "동결이 예상됩니다. 향후 추가 인하에 대한 가이던스가 국채 및 외환 시장에 핵심입니다.",
    correlationEn: "BOK hold + dovish guidance → Korean bonds rally mildly → KRW stable.",
    correlationKo: "한국은행 동결 + 비둘기파 가이던스 → 국채 소폭 상승 → 원화 안정.",
    counterIndicatorEn: "USD/KRW, Korean 10Y Bond, KOSPI",
    counterIndicatorKo: "달러/원, 국고채 10년, 코스피"
  },
  {
    id: "2026-05-28-korea-cpi",
    time: "2026-05-27T23:00:00Z",
    indicator: "Korea CPI (YoY)",
    indicatorKo: "한국 소비자물가지수 (전년비)",
    importance: "Medium",
    previous: "2.1%",
    forecast: "2.0%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Inflation",
    definitionEn: "Korea's monthly consumer inflation reading. The BOK targets 2% inflation, making this figure central to rate decisions.",
    definitionKo: "한국의 월간 소비자물가 수치입니다. 한국은행의 2% 물가 목표 때문에, 이 수치는 금리 결정의 핵심입니다.",
    impactEn: "CPI at 2% target supports BOK hold decision. Below target opens door to resumed cuts.",
    impactKo: "CPI가 2% 목표에 도달하면 한국은행 동결을 지지합니다. 목표 이하면 금리 인하 재개 여지가 생깁니다.",
    correlationEn: "Low Korea CPI → BOK dovish → KOSPI consumer and rate-sensitive sectors benefit.",
    correlationKo: "낮은 한국 CPI → 한국은행 비둘기파 → 코스피 소비 및 금리 민감 섹터 수혜.",
    counterIndicatorEn: "BOK Base Rate, Korean Retail Sales",
    counterIndicatorKo: "한국은행 기준금리, 한국 소매 판매"
  },

  // ===== KR / JP / EU EVENTS — JUNE 2026 =====
  {
    id: "2026-06-05-ecb-decision",
    time: "2026-06-05T13:15:00Z",
    indicator: "ECB Interest Rate Decision",
    indicatorKo: "유럽중앙은행(ECB) 기준금리 결정",
    importance: "High",
    previous: "2.25%",
    forecast: "2.00%",
    actual: null,
    unit: "%",
    country: "EU",
    category: "Central Bank",
    definitionEn: "June ECB meeting coincides with updated ECB staff projections. Rate cut decisions are calibrated against eurozone inflation, growth, and financial stability.",
    definitionKo: "6월 ECB 회의는 ECB 직원 경제 전망 업데이트와 함께 진행됩니다. 금리 인하 결정은 유로존 인플레이션, 성장, 금융 안정성을 고려하여 결정됩니다.",
    impactEn: "Third consecutive ECB cut → Confirms European easing cycle → EUR weakens further → Boosts EU equities.",
    impactKo: "ECB 세 번째 연속 금리 인하 → 유럽 완화 사이클 확인 → 유로화 추가 약세 → EU 주식 지지.",
    correlationEn: "ECB triple cut → EUR/USD tests parity zone → European companies with USD revenues outperform.",
    correlationKo: "ECB 세 번 연속 인하 → 유로/달러 패리티 구간 테스트 → 달러 매출 유럽 기업 아웃퍼폼.",
    counterIndicatorEn: "EUR/USD, Eurozone GDP, EuroStoxx 50",
    counterIndicatorKo: "유로/달러, 유로존 GDP, 유로스톡스50"
  },
  {
    id: "2026-06-16-boj-decision",
    time: "2026-06-16T03:00:00Z",
    indicator: "Bank of Japan Policy Rate Decision",
    indicatorKo: "일본은행(BOJ) 정책금리 결정",
    importance: "High",
    previous: "0.50%",
    forecast: "0.75%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Central Bank",
    definitionEn: "The BOJ June meeting is critical as it includes updated economic outlook. Any rate hike signal triggers global market repositioning through yen dynamics.",
    definitionKo: "BOJ 6월 회의는 경제 전망 업데이트를 포함하여 매우 중요합니다. 금리 인상 신호는 엔화 역학을 통한 글로벌 시장 재조정을 촉발합니다.",
    impactEn: "Hike scenario: JPY surges 2-3% → Nikkei falls 3-5% → EM sell-off from carry unwind. Hold: Status quo.",
    impactKo: "인상 시나리오: 엔화 2-3% 급등 → 닛케이 3-5% 하락 → 캐리 청산으로 신흥국 매도. 동결: 현상 유지.",
    correlationEn: "BOJ hike → Most impactful Central Bank event in Asia → Cascading effects on global risk assets.",
    correlationKo: "BOJ 금리 인상 → 아시아 최대 영향력의 중앙은행 이벤트 → 글로벌 위험 자산에 연쇄 영향.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, KOSPI, S&P 500 Futures",
    counterIndicatorKo: "달러/엔, 닛케이225, 코스피, S&P 500 선물"
  },
  {
    id: "2026-06-18-japan-cpi",
    time: "2026-06-17T23:30:00Z",
    indicator: "Japan CPI (YoY)",
    indicatorKo: "일본 소비자물가지수 (전년비)",
    importance: "High",
    previous: "3.3%",
    forecast: "3.2%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Inflation",
    definitionEn: "Japan's May CPI released in June. The trend of Japanese inflation feeds directly into BOJ rate decisions and shapes global currency dynamics.",
    definitionKo: "6월에 발표되는 일본 5월 CPI입니다. 일본 물가 추세는 BOJ 금리 결정에 직접 반영되며 글로벌 통화 역학을 형성합니다.",
    impactEn: "Pre-BOJ CPI critical for rate decision. Sticky inflation → BOJ hike probability rises → JPY strength.",
    impactKo: "BOJ 결정 이전 CPI가 매우 중요합니다. 끈적한 인플레이션 → BOJ 금리 인상 확률 상승 → 엔화 강세.",
    correlationEn: "Japan inflation trends affect global risk sentiment due to yen carry trade size (~$4 trillion).",
    correlationKo: "일본 물가 추세는 엔 캐리트레이드 규모(약 4조 달러)로 인해 글로벌 위험 심리에 영향을 미칩니다.",
    counterIndicatorEn: "USD/JPY, Yen Carry Basket, Global Equities",
    counterIndicatorKo: "달러/엔, 엔 캐리 바스켓, 글로벌 주식"
  },
  {
    id: "2026-06-24-bok-decision",
    time: "2026-06-24T01:00:00Z",
    indicator: "Bank of Korea Rate Decision",
    indicatorKo: "한국은행(BOK) 기준금리 결정",
    importance: "Medium",
    previous: "2.25%",
    forecast: "2.00%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Central Bank",
    definitionEn: "Bank of Korea policy meeting. With inflation near target and global easing, the BOK evaluates a further cut to stimulate domestic demand.",
    definitionKo: "한국은행 정책 회의입니다. 물가가 목표에 근접하고 글로벌 완화 기조 속에서, 한국은행은 내수 진작을 위한 추가 인하를 검토합니다.",
    impactEn: "Another cut would push the base rate to the lowest level since 2021, supporting domestic mortgage and credit markets.",
    impactKo: "추가 인하 시 기준금리가 2021년 이후 최저 수준으로, 국내 주택담보대출 및 신용 시장을 지지합니다.",
    correlationEn: "BOK cut → Korean REIT sector rallies → Construction stocks benefit → KRW modestly weaker.",
    correlationKo: "한국은행 금리 인하 → 국내 리츠 섹터 상승 → 건설주 수혜 → 원화 소폭 약세.",
    counterIndicatorEn: "Korean REIT Index, Construction Sector ETF",
    counterIndicatorKo: "한국 리츠 지수, 건설주 ETF"
  },

  // ===== KR / JP / EU EVENTS — JULY 2026 =====
  {
    id: "2026-07-17-japan-cpi",
    time: "2026-07-16T23:30:00Z",
    indicator: "Japan CPI (YoY)",
    indicatorKo: "일본 소비자물가지수 (전년비)",
    importance: "High",
    previous: "3.2%",
    forecast: "3.0%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Inflation",
    definitionEn: "June CPI data released in July. Closely watched before the late July BOJ meeting. Any deceleration in inflation may pause the BOJ's rate hike cycle.",
    definitionKo: "7월에 발표되는 6월 CPI 데이터입니다. 7월 말 BOJ 회의를 앞두고 면밀히 주목받습니다. 인플레이션 둔화는 BOJ 금리 인상 사이클을 멈출 수 있습니다.",
    impactEn: "Slowing Japan CPI → BOJ may pause → JPY weakens → Nikkei recovers → Carry trade partially restored.",
    impactKo: "일본 CPI 둔화 → BOJ 인상 일시 중단 가능 → 엔화 약세 → 닛케이 회복 → 캐리트레이드 부분 복원.",
    correlationEn: "Japan CPI deceleration → USD/JPY rebounds → Risk-on globally → EM assets recover.",
    correlationKo: "일본 CPI 둔화 → 달러/엔 반등 → 글로벌 위험 선호 → 신흥국 자산 회복.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, MSCI EM Index",
    counterIndicatorKo: "달러/엔, 닛케이225, MSCI 신흥국 지수"
  },
  {
    id: "2026-07-23-boj-decision",
    time: "2026-07-23T03:00:00Z",
    indicator: "Bank of Japan Policy Rate Decision",
    indicatorKo: "일본은행(BOJ) 정책금리 결정",
    importance: "High",
    previous: "0.75%",
    forecast: "0.75%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Central Bank",
    definitionEn: "The July BOJ meeting. Markets watch whether the BOJ signals a pause in its hiking cycle or continues normalization. Global risk assets are highly sensitive.",
    definitionKo: "7월 BOJ 회의입니다. 시장은 BOJ가 금리 인상 사이클을 일시 중단할지 정상화를 계속할지 주목합니다. 글로벌 위험 자산이 매우 민감하게 반응합니다.",
    impactEn: "BOJ hold likely but hawkish guidance keeps JPY supported. Rate path clarity reduces yen volatility.",
    impactKo: "BOJ 동결 예상이지만 매파적 가이던스로 엔화 지지. 금리 경로 명확화로 엔화 변동성 감소.",
    correlationEn: "BOJ hold + dovish shift → JPY weakens → Nikkei rallies → Risk-on in Asian markets.",
    correlationKo: "BOJ 동결 + 비둘기파 전환 → 엔화 약세 → 닛케이 상승 → 아시아 시장 위험 선호.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, JGB 10Y Yield",
    counterIndicatorKo: "달러/엔, 닛케이225, 일본 국채 10년 수익률"
  },
  {
    id: "2026-07-24-ecb-decision",
    time: "2026-07-24T13:15:00Z",
    indicator: "ECB Interest Rate Decision",
    indicatorKo: "유럽중앙은행(ECB) 기준금리 결정",
    importance: "High",
    previous: "2.00%",
    forecast: "2.00%",
    actual: null,
    unit: "%",
    country: "EU",
    category: "Central Bank",
    definitionEn: "July ECB meeting. After several cuts, the Governing Council assesses whether the neutral rate has been reached and adjusts the pace of easing accordingly.",
    definitionKo: "7월 ECB 회의입니다. 여러 차례 인하 이후, 이사회는 중립금리에 도달했는지 평가하고 완화 속도를 조정합니다.",
    impactEn: "ECB pause likely as rates approach neutral. Focus shifts to forward guidance. EUR stabilizes.",
    impactKo: "금리가 중립 수준에 근접함에 따라 ECB 동결이 예상됩니다. 포워드 가이던스가 초점이 됩니다. 유로화 안정.",
    correlationEn: "ECB pause at neutral → EUR/USD stabilizes → European equities consolidate.",
    correlationKo: "ECB 중립금리에서 동결 → 유로/달러 안정화 → 유럽 주식 횡보.",
    counterIndicatorEn: "EUR/USD, EuroStoxx 50, Eurozone CPI",
    counterIndicatorKo: "유로/달러, 유로스톡스50, 유로존 CPI"
  },
  {
    id: "2026-07-10-bok-decision",
    time: "2026-07-10T01:00:00Z",
    indicator: "Bank of Korea Rate Decision",
    indicatorKo: "한국은행(BOK) 기준금리 결정",
    importance: "Medium",
    previous: "2.00%",
    forecast: "2.00%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Central Bank",
    definitionEn: "Bank of Korea July meeting. Following rate cuts, the BOK monitors domestic economic recovery and external risks before deciding next steps.",
    definitionKo: "한국은행 7월 회의입니다. 금리 인하 이후, 한국은행은 다음 단계를 결정하기 전에 국내 경기 회복과 외부 위험을 모니터링합니다.",
    impactEn: "BOK hold expected. Focus on economic assessment and any signals for H2 2026 rate path.",
    impactKo: "한국은행 동결 예상. 경제 평가와 2026년 하반기 금리 경로에 대한 신호에 초점.",
    correlationEn: "BOK hold → KOSPI stable → USD/KRW range-bound.",
    correlationKo: "한국은행 동결 → 코스피 안정 → 달러/원 박스권.",
    counterIndicatorEn: "USD/KRW, KOSPI, Korean GDP",
    counterIndicatorKo: "달러/원 환율, 코스피, 한국 GDP"
  },

  // ===== KR / JP / EU EVENTS — AUGUST 2026 =====
  {
    id: "2026-08-20-japan-cpi",
    time: "2026-08-19T23:30:00Z",
    indicator: "Japan CPI (YoY)",
    indicatorKo: "일본 소비자물가지수 (전년비)",
    importance: "Medium",
    previous: "3.0%",
    forecast: "2.9%",
    actual: null,
    unit: "%",
    country: "JPN",
    category: "Inflation",
    definitionEn: "Japan's July CPI. Released ahead of September BOJ meeting. A cooling trend would support a pause in the BOJ's rate hike cycle.",
    definitionKo: "일본 7월 CPI입니다. 9월 BOJ 회의를 앞두고 발표됩니다. 냉각 추세는 BOJ 금리 인상 사이클 일시 중단을 지지할 것입니다.",
    impactEn: "Moderating Japan inflation → BOJ patience → JPY carry trade partially revives → Risk-on in EM.",
    impactKo: "일본 인플레이션 완화 → BOJ 인내심 → 엔 캐리트레이드 부분 부활 → 신흥국 위험 선호.",
    correlationEn: "Japan CPI below 3% → Yen weakens moderately → Nikkei benefits → Global risk assets recover.",
    correlationKo: "일본 CPI 3% 미만 → 엔화 소폭 약세 → 닛케이 수혜 → 글로벌 위험 자산 회복.",
    counterIndicatorEn: "USD/JPY, Nikkei 225, JGB 2Y Yield",
    counterIndicatorKo: "달러/엔, 닛케이225, 일본 국채 2년 수익률"
  },
  {
    id: "2026-08-27-bok-decision",
    time: "2026-08-27T01:00:00Z",
    indicator: "Bank of Korea Rate Decision",
    indicatorKo: "한국은행(BOK) 기준금리 결정",
    importance: "Medium",
    previous: "2.00%",
    forecast: "2.00%",
    actual: null,
    unit: "%",
    country: "KOR",
    category: "Central Bank",
    definitionEn: "Bank of Korea August meeting. With the global rate cycle stabilizing, the BOK's focus turns to domestic growth and the Korean housing market.",
    definitionKo: "한국은행 8월 회의입니다. 글로벌 금리 사이클이 안정됨에 따라, 한국은행의 초점은 국내 성장과 주택 시장으로 이동합니다.",
    impactEn: "BOK hold with stable guidance. Market attention on BOK assessment of housing price risks.",
    impactKo: "안정적 가이던스와 함께 한국은행 동결. 한국은행의 주택가격 위험 평가에 시장 주목.",
    correlationEn: "BOK hold → Korean bond yields stable → KOSPI tracks global sentiment.",
    correlationKo: "한국은행 동결 → 국채 수익률 안정 → 코스피는 글로벌 심리를 추종.",
    counterIndicatorEn: "Korean Housing Price Index, KOSPI",
    counterIndicatorKo: "한국 주택가격지수, 코스피"
  },
  {
    id: "2026-08-25-ecb-jackson",
    time: "2026-08-25T14:00:00Z",
    indicator: "ECB President Speech (Jackson Hole)",
    indicatorKo: "ECB 총재 연설 (잭슨홀)",
    importance: "High",
    previous: null,
    forecast: null,
    actual: null,
    unit: null,
    country: "EU",
    category: "Central Bank",
    definitionEn: "The ECB President's speech at the Federal Reserve's annual Jackson Hole Economic Symposium. A key venue for signaling future monetary policy direction for the Eurozone.",
    definitionKo: "연준 연례 잭슨홀 경제 심포지엄에서의 ECB 총재 연설입니다. 유로존 미래 통화 정책 방향을 시사하는 핵심 자리입니다.",
    impactEn: "Hawkish signals → EUR strengthens. Dovish signals → EUR weakens, European equities rally. Coordination with Fed policy important.",
    impactKo: "매파적 신호 → 유로화 강세. 비둘기파적 신호 → 유로화 약세, 유럽 주식 상승. 연준 정책과의 조율이 중요합니다.",
    correlationEn: "ECB-Fed policy divergence signals → EUR/USD volatile → Cross-asset repricing across global markets.",
    correlationKo: "ECB-연준 정책 차이 신호 → 유로/달러 변동 → 글로벌 시장 전반의 자산 재가격화.",
    counterIndicatorEn: "EUR/USD, EuroStoxx 50, Global Bond Yields",
    counterIndicatorKo: "유로/달러, 유로스톡스50, 글로벌 채권 수익률"
  }
];

export function getEventsByMonth(year: number, month: number): EconomicEvent[] {
  return EVENTS.filter(event => {
    const d = new Date(event.time);
    return d.getUTCFullYear() === year && (d.getUTCMonth() + 1) === month;
  });
}

export function getEventsByDateRange(start: Date, end: Date): EconomicEvent[] {
  return EVENTS.filter(event => {
    const d = new Date(event.time);
    return d >= start && d <= end;
  });
}
