export interface Holding {
  ticker: string;
  company: string;
  sector: string;
  shares: number;
  weight: number;
  change: "Bought" | "Sold" | "Held" | "New";
  changePct: number | null;
  whyTheyBoughtEn: string;
  whyTheyBoughtKo: string;
  priceApprox?: number;
}

export interface SectorAllocation {
  sector: string;
  weight: number;
  color: string;
}

export type InvestorCategory = "value" | "growth" | "macro" | "hedge" | "activist" | "sovereign" | "index";

export interface SuperInvestor {
  id: string;
  name: string;
  firm: string;
  country: string;
  aum: number;
  aumUnit: string;
  initials: string;
  avatarColor: string;
  category: InvestorCategory;
  biographyEn: string;
  biographyKo: string;
  styleEn: string;
  styleKo: string;
  styleTagsEn: string[];
  styleTagsKo: string[];
  lastUpdated: string;
  filingType: string;
  sectorAllocation: SectorAllocation[];
  holdings: Holding[];
}

export const SUPER_INVESTORS: SuperInvestor[] = [
  // ─── VALUE ───────────────────────────────────────────────────────────────────
  {
    id: "buffett",
    name: "Warren Buffett",
    firm: "Berkshire Hathaway",
    country: "US",
    aum: 291,
    aumUnit: "B",
    initials: "WB",
    avatarColor: "#2563eb",
    category: "value",
    biographyEn: "Known as the 'Oracle of Omaha,' Warren Buffett began investing at age 11 and built Berkshire Hathaway into a $700B+ conglomerate. His mentor Benjamin Graham taught him value investing principles.",
    biographyKo: "'오마하의 현인' 워렌 버핏은 11세에 투자를 시작해 버크셔 해서웨이를 7000억 달러 이상의 기업으로 키웠습니다. 스승 벤저민 그레이엄에게 가치투자를 배웠습니다.",
    styleEn: "Value investing with a long-term horizon. Focuses on businesses with durable competitive moats, predictable cash flows, and excellent management.",
    styleKo: "장기적 가치 투자. 지속적인 경쟁 우위, 예측 가능한 현금 흐름, 뛰어난 경영진을 갖춘 기업에 집중합니다.",
    styleTagsEn: ["Value Investing", "Long-Term", "Economic Moat", "Dividends"],
    styleTagsKo: ["가치 투자", "장기 투자", "경제적 해자", "배당주"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Financials", weight: 36.2, color: "#3b82f6" },
      { sector: "Technology", weight: 25.8, color: "#8b5cf6" },
      { sector: "Consumer Staples", weight: 12.1, color: "#10b981" },
      { sector: "Energy", weight: 11.4, color: "#f59e0b" },
      { sector: "Healthcare", weight: 6.8, color: "#ef4444" },
      { sector: "Communications", weight: 4.7, color: "#06b6d4" },
      { sector: "Other", weight: 3.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 300000000, weight: 25.8, change: "Sold", changePct: -22.4, whyTheyBoughtEn: "Buffett sees Apple as a consumer products company with unmatched brand loyalty. It generates enormous free cash flow and returns capital via buybacks.", whyTheyBoughtKo: "버핏은 애플을 타의 추종을 불허하는 브랜드 충성도를 가진 소비재 회사로 봅니다. 거대한 자유 현금 흐름을 창출하고 자사주 매입을 통해 자본을 환원합니다." },
      { ticker: "AXP", company: "American Express", sector: "Financials", shares: 151610700, weight: 15.1, change: "Held", changePct: 0, whyTheyBoughtEn: "American Express has a unique closed-loop network targeting affluent customers who spend more and default less. Its brand is a moat.", whyTheyBoughtKo: "아메리칸 익스프레스는 더 많이 소비하고 덜 연체하는 부유한 고객을 대상으로 하는 독특한 폐쇄형 네트워크를 보유합니다." },
      { ticker: "BAC", company: "Bank of America", sector: "Financials", shares: 680000000, weight: 11.3, change: "Sold", changePct: -12.1, whyTheyBoughtEn: "One of America's largest banks with massive scale advantages. Benefits from rising interest rates as a net interest income earner.", whyTheyBoughtKo: "거대한 규모 우위를 갖춘 미국 최대 은행 중 하나입니다. 순이자 수익 창출자로서 금리 상승의 혜택을 받습니다." },
      { ticker: "KO", company: "Coca-Cola", sector: "Consumer Staples", shares: 400000000, weight: 8.7, change: "Held", changePct: 0, whyTheyBoughtEn: "Buffett's most iconic long-term holding since 1988. Coca-Cola operates in 200+ countries with consistent dividends and unrivaled brand power.", whyTheyBoughtKo: "1988년부터 버핏의 가장 상징적인 장기 보유 종목. 200개 이상의 국가에서 운영되며 일관된 배당금과 타의 추종을 불허하는 브랜드를 보유합니다." },
      { ticker: "CVX", company: "Chevron Corp", sector: "Energy", shares: 118262602, weight: 5.2, change: "Sold", changePct: -8.3, whyTheyBoughtEn: "Major integrated oil company with strong cash generation and attractive dividend yield. Buffett sees energy as essential infrastructure.", whyTheyBoughtKo: "강력한 현금 창출과 매력적인 배당 수익률을 갖춘 주요 통합 석유 회사입니다. 버핏은 에너지를 필수 인프라로 봅니다." },
      { ticker: "OXY", company: "Occidental Petroleum", sector: "Energy", shares: 264800000, weight: 6.2, change: "Bought", changePct: 4.8, whyTheyBoughtEn: "Buffett aggressively built this position for its US onshore oil assets and CEO Vicki Hollub's disciplined capital allocation.", whyTheyBoughtKo: "버핏은 미국 육상 석유 자산과 비키 홀럽 CEO의 규율 있는 자본 배분으로 이 포지션을 공격적으로 구축했습니다." },
      { ticker: "MCO", company: "Moody's Corp", sector: "Financials", shares: 24669778, weight: 2.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Moody's has massive switching costs, recurring revenue, near-zero capital requirements, and extraordinary ROE — a toll road on global debt markets.", whyTheyBoughtKo: "무디스는 막대한 전환 비용, 반복 수익, 거의 제로 자본 요구량, 탁월한 ROE를 갖추고 있습니다 — 글로벌 채권 시장의 유료 도로입니다." },
      { ticker: "KHC", company: "Kraft Heinz", sector: "Consumer Staples", shares: 325634818, weight: 3.1, change: "Held", changePct: 0, whyTheyBoughtEn: "A challenged position Buffett has admitted was an overpayment. Despite iconic brands, changing consumer tastes hurt the thesis.", whyTheyBoughtKo: "버핏이 과지불이었음을 인정한 어려운 포지션입니다. 상징적인 브랜드에도 불구하고 소비자 기호 변화가 투자 논거를 약화시켰습니다." },
      { ticker: "DVA", company: "DaVita Inc.", sector: "Healthcare", shares: 36095570, weight: 1.9, change: "Held", changePct: 0, whyTheyBoughtEn: "Kidney dialysis is a necessity — patients cannot skip treatment. DaVita runs the largest US dialysis network with predictable, recurring revenue.", whyTheyBoughtKo: "신장 투석은 필수입니다. 다비타는 예측 가능하고 반복적인 수익을 가진 미국 최대 투석 네트워크를 운영합니다." },
      { ticker: "VRSN", company: "VeriSign Inc.", sector: "Communications", shares: 13259468, weight: 1.6, change: "Held", changePct: 0, whyTheyBoughtEn: "VeriSign owns the exclusive contract to manage .com and .net domains — a government-backed monopoly with pricing power and near-zero capex.", whyTheyBoughtKo: ".com 및 .net 도메인을 독점 관리하는 정부 보장 독점 기업입니다. 가격 결정력과 거의 제로의 자본 지출을 보유합니다." },
    ],
  },

  {
    id: "klarman",
    name: "Seth Klarman",
    firm: "Baupost Group",
    country: "US",
    aum: 32,
    aumUnit: "B",
    initials: "SK",
    avatarColor: "#1e40af",
    category: "value",
    biographyEn: "Seth Klarman founded Baupost Group in 1982 and is one of the most secretive and successful hedge fund managers in history. His book 'Margin of Safety' is considered a bible of value investing.",
    biographyKo: "세스 클라만은 1982년 바우포스트 그룹을 설립했으며 역사상 가장 비밀스럽고 성공적인 헤지펀드 매니저 중 한 명입니다. 그의 책 '안전마진'은 가치 투자의 성서로 여겨집니다.",
    styleEn: "Deep value with a heavy focus on margin of safety. Invests across asset classes including distressed debt, real estate, and equities. Keeps significant cash reserves to deploy during crises.",
    styleKo: "안전마진에 중점을 둔 심층 가치 투자. 부실 채권, 부동산, 주식 등 다양한 자산에 투자합니다. 위기 시 배포를 위해 상당한 현금 보유량을 유지합니다.",
    styleTagsEn: ["Deep Value", "Margin of Safety", "Distressed Assets", "Cash Heavy"],
    styleTagsKo: ["심층 가치", "안전마진", "부실자산", "현금 중심"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Healthcare", weight: 31.2, color: "#ef4444" },
      { sector: "Technology", weight: 22.4, color: "#8b5cf6" },
      { sector: "Financials", weight: 18.7, color: "#3b82f6" },
      { sector: "Consumer", weight: 14.1, color: "#f59e0b" },
      { sector: "Cash / Bonds", weight: 13.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "QRTEA", company: "Qurate Retail", sector: "Consumer", shares: 68000000, weight: 8.2, change: "Held", changePct: 0, whyTheyBoughtEn: "Classic Klarman distressed play — trading at deep discount to intrinsic value with complex capital structure creating opportunity.", whyTheyBoughtKo: "전형적인 클라만의 부실 투자 — 복잡한 자본구조가 기회를 창출하며 내재 가치 대비 심각하게 할인된 가격에 거래됩니다." },
      { ticker: "EVERI", company: "Everi Holdings", sector: "Technology", shares: 24000000, weight: 7.6, change: "New", changePct: null, whyTheyBoughtEn: "Gaming technology company with recurring revenue from casino management systems. Klarman sees undiscovered value in niche market leadership.", whyTheyBoughtKo: "카지노 관리 시스템의 반복 수익을 가진 게임 기술 회사입니다. 클라만은 틈새 시장 리더십에서 미발견 가치를 봅니다." },
      { ticker: "PTC", company: "PTC Inc.", sector: "Technology", shares: 8200000, weight: 9.4, change: "Bought", changePct: 12.3, whyTheyBoughtEn: "Industrial software with high switching costs and subscription model. Dominant in CAD/PLM with strong recurring revenues.", whyTheyBoughtKo: "높은 전환 비용과 구독 모델을 가진 산업용 소프트웨어입니다. CAD/PLM 분야 지배적 위치와 강한 반복 수익을 보유합니다." },
      { ticker: "CRISPR", company: "CRISPR Therapeutics", sector: "Healthcare", shares: 5600000, weight: 6.1, change: "Held", changePct: 0, whyTheyBoughtEn: "Biotech with transformational gene-editing technology. Trading at discount to pipeline value with FDA approvals catalyzing upside.", whyTheyBoughtKo: "혁신적 유전자 편집 기술을 가진 바이오텍입니다. 파이프라인 가치 대비 할인 거래되며 FDA 승인이 상승 동력입니다." },
      { ticker: "WPM", company: "Wheaton Precious Metals", sector: "Materials", shares: 12000000, weight: 5.8, change: "Bought", changePct: 9.7, whyTheyBoughtEn: "Gold and silver streaming business with royalty-like cash flows. Inflation hedge with leverage to precious metals without mining operational risk.", whyTheyBoughtKo: "로열티와 같은 현금 흐름을 가진 금은 스트리밍 사업입니다. 채굴 운영 위험 없이 귀금속에 레버리지된 인플레이션 헤지입니다." },
    ],
  },

  {
    id: "icahn",
    name: "Carl Icahn",
    firm: "Icahn Capital",
    country: "US",
    aum: 18,
    aumUnit: "B",
    initials: "CI",
    avatarColor: "#dc2626",
    category: "activist",
    biographyEn: "Carl Icahn is one of America's most famous activist investors, known for taking large stakes in companies and pressuring management for change. His aggressive style has earned him the nickname 'Corporate Raider.'",
    biographyKo: "칼 아이칸은 기업에 대규모 지분을 취득하고 경영진에게 변화를 압박하는 것으로 유명한 미국의 가장 유명한 행동주의 투자자 중 한 명입니다. 그의 공격적인 스타일로 '기업 약탈자'라는 별명을 얻었습니다.",
    styleEn: "Activist investing — takes concentrated positions and pushes for operational improvements, share buybacks, or corporate restructuring to unlock value.",
    styleKo: "행동주의 투자 — 집중 포지션을 취하고 가치 실현을 위해 운영 개선, 자사주 매입 또는 기업 구조조정을 추진합니다.",
    styleTagsEn: ["Activist", "Concentrated", "Restructuring", "Value Creation"],
    styleTagsKo: ["행동주의", "집중 투자", "구조조정", "가치 창출"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Industrials", weight: 28.3, color: "#f59e0b" },
      { sector: "Energy", weight: 22.1, color: "#ef4444" },
      { sector: "Financials", weight: 19.4, color: "#3b82f6" },
      { sector: "Consumer", weight: 18.7, color: "#10b981" },
      { sector: "Other", weight: 11.5, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "IEP", company: "Icahn Enterprises LP", sector: "Diversified", shares: 150000000, weight: 35.2, change: "Held", changePct: 0, whyTheyBoughtEn: "Icahn's own holding company that controls his diversified portfolio of businesses including energy, automotive, and real estate.", whyTheyBoughtKo: "에너지, 자동차, 부동산을 포함한 다각화된 사업 포트폴리오를 통제하는 아이칸 자신의 지주 회사입니다." },
      { ticker: "CVR", company: "CVR Energy", sector: "Energy", shares: 40000000, weight: 12.8, change: "Held", changePct: 0, whyTheyBoughtEn: "Petroleum refiner and fertilizer producer with strong free cash flow generation. Icahn controls the company and extracts value through dividends.", whyTheyBoughtKo: "강력한 자유 현금 흐름을 창출하는 석유 정제업체 및 비료 생산업체입니다. 아이칸은 회사를 통제하고 배당금을 통해 가치를 창출합니다." },
      { ticker: "SBUX", company: "Starbucks", sector: "Consumer", shares: 15000000, weight: 9.4, change: "New", changePct: null, whyTheyBoughtEn: "Activist position pushing for operational improvements and new CEO selection. Believes Starbucks brand value significantly exceeds its depressed stock price.", whyTheyBoughtKo: "운영 개선과 새 CEO 선임을 위한 행동주의 포지션입니다. 스타벅스 브랜드 가치가 하락한 주가를 크게 상회한다고 봅니다." },
      { ticker: "BIIB", company: "Biogen", sector: "Healthcare", shares: 5200000, weight: 8.7, change: "Sold", changePct: -18.3, whyTheyBoughtEn: "Large pharma with pipeline assets and cost-cutting potential. Icahn pushed for merger consideration to unlock value for shareholders.", whyTheyBoughtKo: "파이프라인 자산과 비용 절감 잠재력을 가진 대형 제약사입니다. 아이칸은 주주 가치 실현을 위해 합병 검토를 촉구했습니다." },
    ],
  },

  {
    id: "einhorn",
    name: "David Einhorn",
    firm: "Greenlight Capital",
    country: "US",
    aum: 2.1,
    aumUnit: "B",
    initials: "DE",
    avatarColor: "#059669",
    category: "value",
    biographyEn: "David Einhorn founded Greenlight Capital in 1996. He became famous for shorting Lehman Brothers before its 2008 collapse and his long/short value approach. He also plays poker at an elite level.",
    biographyKo: "데이비드 아인혼은 1996년 그린라이트 캐피털을 설립했습니다. 2008년 붕괴 전 리먼 브라더스를 공매도하고 롱/숏 가치 접근법으로 유명해졌습니다.",
    styleEn: "Long/short value approach combining fundamental analysis with short selling of overvalued companies. Known for deep research and willingness to take contrarian positions.",
    styleKo: "기본 분석과 고평가 기업의 공매도를 결합한 롱/숏 가치 접근법. 심층 리서치와 역발상 포지션 취하기로 유명합니다.",
    styleTagsEn: ["Long/Short", "Value", "Contrarian", "Short Selling"],
    styleTagsKo: ["롱/숏", "가치", "역발상", "공매도"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 35.2, color: "#8b5cf6" },
      { sector: "Financials", weight: 24.6, color: "#3b82f6" },
      { sector: "Consumer", weight: 18.3, color: "#f59e0b" },
      { sector: "Healthcare", weight: 14.2, color: "#ef4444" },
      { sector: "Other", weight: 7.7, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "GOOGL", company: "Alphabet Inc.", sector: "Technology", shares: 2800000, weight: 22.4, change: "Bought", changePct: 15.8, whyTheyBoughtEn: "Einhorn sees Alphabet trading at a steep discount to the sum of its parts — Search, YouTube, Google Cloud each worth more separately than the depressed market cap.", whyTheyBoughtKo: "아인혼은 알파벳이 각 부문(검색, 유튜브, 구글 클라우드) 합산 가치 대비 크게 할인 거래된다고 봅니다." },
      { ticker: "BRK.B", company: "Berkshire Hathaway", sector: "Financials", shares: 5600000, weight: 18.3, change: "Bought", changePct: 8.4, whyTheyBoughtEn: "Berkshire trades at a discount to intrinsic value with massive cash pile and Buffett's continued capital allocation ability.", whyTheyBoughtKo: "버크셔는 막대한 현금 보유고와 버핏의 지속적인 자본 배분 능력으로 내재 가치 대비 할인 거래됩니다." },
      { ticker: "GOLD", company: "Barrick Gold", sector: "Materials", shares: 18000000, weight: 12.7, change: "Held", changePct: 0, whyTheyBoughtEn: "Inflation hedge and dollar debasement play. Barrick has high-quality assets with low costs, trading at discount to NAV of its gold reserves.", whyTheyBoughtKo: "인플레이션 헤지와 달러 가치 하락 방어입니다. 배릭은 낮은 비용의 고품질 자산을 보유하며 금 매장량 순자산가치 대비 할인 거래됩니다." },
      { ticker: "OHI", company: "Omega Healthcare", sector: "Healthcare", shares: 8400000, weight: 9.6, change: "New", changePct: null, whyTheyBoughtEn: "Healthcare REIT with attractive dividend yield from skilled nursing facilities. Demographics favor aging population tailwinds.", whyTheyBoughtKo: "요양원에서 매력적인 배당 수익률을 제공하는 헬스케어 REIT입니다. 고령화 인구 트렌드가 유리하게 작용합니다." },
    ],
  },

  {
    id: "pabrai",
    name: "Mohnish Pabrai",
    firm: "Pabrai Investments",
    country: "US",
    aum: 0.9,
    aumUnit: "B",
    initials: "MP",
    avatarColor: "#0891b2",
    category: "value",
    biographyEn: "Mohnish Pabrai is a self-made Indian-American investor who cloned Buffett's approach. He famously paid $650,100 to have lunch with Buffett. His 'Dhando Investor' framework emphasizes 'heads I win, tails I don't lose much.'",
    biographyKo: "모니시 파브라이는 버핏의 접근 방식을 복제한 자수성가한 인도계 미국인 투자자입니다. 버핏과의 점심 식사를 위해 65만 100달러를 지불한 것으로 유명합니다. 그의 '단도 투자자' 프레임워크는 '이기면 좋고, 지더라도 손실이 적다'를 강조합니다.",
    styleEn: "Concentrated value investing inspired by Buffett and Munger. Holds 5-10 stocks, invests only when there is a massive margin of safety, and focuses on asymmetric risk/reward.",
    styleKo: "버핏과 멍거에서 영감을 받은 집중 가치 투자. 5-10개 종목만 보유하고 큰 안전마진이 있을 때만 투자하며 비대칭 리스크/보상에 집중합니다.",
    styleTagsEn: ["Concentrated", "Value Cloning", "Asymmetric Risk", "Margin of Safety"],
    styleTagsKo: ["집중 투자", "가치 복제", "비대칭 리스크", "안전마진"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 42.3, color: "#8b5cf6" },
      { sector: "Consumer", weight: 28.7, color: "#f59e0b" },
      { sector: "Financials", weight: 18.4, color: "#3b82f6" },
      { sector: "Other", weight: 10.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "META", company: "Meta Platforms", sector: "Technology", shares: 1200000, weight: 28.4, change: "Bought", changePct: 34.2, whyTheyBoughtEn: "Pabrai bought Meta at trough valuation when Zuckerberg was scorned for metaverse spending. Classic heads-I-win play — advertising duopoly with massive FCF.", whyTheyBoughtKo: "파브라이는 저커버그가 메타버스 지출로 비난받을 때 저점 밸류에이션에 메타를 매수했습니다. 전형적인 '이기면 좋고' 플레이 — 막대한 FCF를 가진 광고 복점." },
      { ticker: "ALSN", company: "Allison Transmission", sector: "Industrials", shares: 4800000, weight: 18.7, change: "Held", changePct: 0, whyTheyBoughtEn: "Monopoly-like position in automatic transmission for commercial vehicles with 50%+ market share. Recurring maintenance revenues and pricing power.", whyTheyBoughtKo: "상업용 차량 자동 변속기에서 50% 이상의 시장 점유율로 독점적 위치를 점합니다. 반복적 유지보수 수익과 가격 결정력을 보유합니다." },
      { ticker: "RAIN", company: "Rain Industries", sector: "Materials", shares: 12000000, weight: 14.2, change: "New", changePct: null, whyTheyBoughtEn: "Indian conglomerate with calcined petroleum coke business — essential material for aluminum smelting with limited substitutes and pricing power.", whyTheyBoughtKo: "알루미늄 제련에 필수적인 한정된 대체재와 가격 결정력을 가진 석유 코크스 사업을 보유한 인도 대기업입니다." },
    ],
  },

  {
    id: "miller",
    name: "Bill Miller",
    firm: "Miller Value Partners",
    country: "US",
    aum: 2.4,
    aumUnit: "B",
    initials: "BM",
    avatarColor: "#7c3aed",
    category: "value",
    biographyEn: "Bill Miller is legendary for beating the S&P 500 for 15 consecutive years (1991-2005) at Legg Mason. He famously bought Amazon in the 1990s when others dismissed it, and later became a Bitcoin believer.",
    biographyKo: "빌 밀러는 레그 메이슨에서 15년 연속(1991-2005) S&P 500을 이긴 것으로 유명합니다. 1990년대 다른 사람들이 무시할 때 아마존을 매수했고 나중에 비트코인 신봉자가 되었습니다.",
    styleEn: "Value investing that ignores conventional valuation metrics, instead focusing on intrinsic value based on future cash flows. Early adopter of disruptive technologies when priced for failure.",
    styleKo: "전통적인 밸류에이션 지표를 무시하고 미래 현금 흐름 기반의 내재 가치에 집중하는 가치 투자. 실패 가격에 거래될 때 혁신 기술의 조기 채택자.",
    styleTagsEn: ["Unconventional Value", "Disruption", "Long-Term FCF", "Contrarian"],
    styleTagsKo: ["비전통적 가치", "혁신", "장기 FCF", "역발상"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 48.2, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 22.4, color: "#ef4444" },
      { sector: "Financials", weight: 17.8, color: "#3b82f6" },
      { sector: "Other", weight: 11.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AMZN", company: "Amazon.com", sector: "Technology", shares: 4200000, weight: 28.3, change: "Held", changePct: 0, whyTheyBoughtEn: "Miller bought Amazon in 1999 and never sold. He understands Amazon's flywheel — each new service strengthens the ecosystem, creating compounding competitive advantages.", whyTheyBoughtKo: "밀러는 1999년 아마존을 매수하고 팔지 않았습니다. 아마존의 플라이휠을 이해합니다 — 각 신규 서비스가 생태계를 강화하여 복리 경쟁 우위를 창출합니다." },
      { ticker: "COIN", company: "Coinbase", sector: "Financials", shares: 5800000, weight: 14.7, change: "Bought", changePct: 22.4, whyTheyBoughtEn: "Regulated crypto exchange with network effects and infrastructure monopoly. Miller sees crypto as a new asset class here to stay, with Coinbase as the dominant on-ramp.", whyTheyBoughtKo: "네트워크 효과와 인프라 독점을 가진 규제된 암호화폐 거래소입니다. 밀러는 암호화폐를 지속될 새 자산 클래스로, 코인베이스를 지배적 진입 통로로 봅니다." },
      { ticker: "CLBT", company: "Cellebrite DI", sector: "Technology", shares: 28000000, weight: 12.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Digital intelligence company serving law enforcement with high switching costs and subscription revenue. Niche monopoly in digital forensics.", whyTheyBoughtKo: "높은 전환 비용과 구독 수익을 가진 법 집행 기관을 위한 디지털 인텔리전스 회사입니다. 디지털 포렌식의 틈새 독점 기업입니다." },
    ],
  },

  // ─── GROWTH ────────────────────────────────────────────────────────────────
  {
    id: "coleman",
    name: "Chase Coleman III",
    firm: "Tiger Global Management",
    country: "US",
    aum: 58,
    aumUnit: "B",
    initials: "CC",
    avatarColor: "#f59e0b",
    category: "growth",
    biographyEn: "Chase Coleman III is a 'Tiger Cub' — he trained under legendary investor Julian Robertson at Tiger Management. Tiger Global became one of the most successful and influential tech-focused hedge funds in history.",
    biographyKo: "체이스 콜먼 3세는 '타이거 새끼' — 타이거 매니지먼트의 전설적인 투자자 줄리안 로버트슨 밑에서 훈련받았습니다. 타이거 글로벌은 역사상 가장 성공적이고 영향력 있는 기술 중심 헤지 펀드 중 하나가 되었습니다.",
    styleEn: "High-conviction technology and consumer internet investing. Focuses on fast-growing companies with strong network effects, switching costs, and runway for massive compounding.",
    styleKo: "확신에 찬 기술 및 소비자 인터넷 투자. 강력한 네트워크 효과, 전환 비용, 대규모 복리 성장 여지를 가진 빠르게 성장하는 회사에 집중합니다.",
    styleTagsEn: ["High-Growth Tech", "Network Effects", "Internet", "Long-Term Compounding"],
    styleTagsKo: ["고성장 기술", "네트워크 효과", "인터넷", "장기 복리"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 62.4, color: "#8b5cf6" },
      { sector: "Consumer Discretionary", weight: 18.7, color: "#f59e0b" },
      { sector: "Healthcare", weight: 10.3, color: "#ef4444" },
      { sector: "Other", weight: 8.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 12000000, weight: 18.4, change: "Bought", changePct: 8.2, whyTheyBoughtEn: "Azure cloud and AI leadership via OpenAI partnership makes Microsoft the infrastructure backbone of the AI era. Coleman views AI monetization as a decade-long compounding opportunity.", whyTheyBoughtKo: "Azure 클라우드와 OpenAI 파트너십을 통한 AI 리더십이 마이크로소프트를 AI 시대의 인프라 중추로 만듭니다. AI 수익화를 10년간의 복리 기회로 봅니다." },
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 5800000, weight: 22.3, change: "Held", changePct: 0, whyTheyBoughtEn: "NVIDIA's GPU monopoly in AI training makes it irreplaceable. Data center revenue compounding at triple digits with no credible GPU competitor.", whyTheyBoughtKo: "AI 훈련에서 엔비디아의 GPU 독점이 대체 불가능하게 만듭니다. 데이터센터 수익이 세 자리 수로 증가하며 믿을 만한 GPU 경쟁자가 없습니다." },
      { ticker: "MELI", company: "MercadoLibre", sector: "Consumer", shares: 780000, weight: 12.7, change: "Bought", changePct: 18.3, whyTheyBoughtEn: "Latin America's dominant e-commerce and fintech platform — the Amazon + PayPal of LATAM. Massive runway in underbanked, under-e-commerced market of 650M people.", whyTheyBoughtKo: "라틴아메리카의 지배적인 전자상거래 및 핀테크 플랫폼 — 남미의 아마존+페이팔. 6.5억 명의 은행 서비스 부족, 전자상거래 미성숙 시장에서 막대한 성장 잠재력." },
      { ticker: "SE", company: "Sea Limited", sector: "Technology", shares: 6200000, weight: 10.4, change: "Sold", changePct: -14.2, whyTheyBoughtEn: "Southeast Asian super-app with gaming (Garena), e-commerce (Shopee), and fintech (SeaMoney). Dominant in the fastest-growing internet market globally.", whyTheyBoughtKo: "게임(가레나), 전자상거래(쇼피), 핀테크(씨머니)를 갖춘 동남아시아 슈퍼앱입니다. 전 세계에서 가장 빠르게 성장하는 인터넷 시장에서 지배적 위치를 점합니다." },
    ],
  },

  {
    id: "wood",
    name: "Cathie Wood",
    firm: "ARK Invest",
    country: "US",
    aum: 11,
    aumUnit: "B",
    initials: "CW",
    avatarColor: "#ec4899",
    category: "growth",
    biographyEn: "Cathie Wood founded ARK Invest in 2014, pioneering thematic ETFs focused on disruptive innovation. ARK became famous for its Tesla calls and 5-year price targets, managing $60B+ at peak in 2021.",
    biographyKo: "캐시 우드는 2014년 혁신 기술 테마 ETF를 개척하며 ARK 인베스트를 설립했습니다. ARK는 테슬라 투자와 5년 목표 주가로 유명해졌으며 2021년 최고조에 600억 달러 이상을 운용했습니다.",
    styleEn: "Disruptive innovation investing across AI, genomics, autonomous vehicles, blockchain, and space. 5-year horizon with high conviction in exponential technology adoption curves.",
    styleKo: "AI, 유전체학, 자율주행, 블록체인, 우주 분야의 혁신 기술 투자. 지수적 기술 채택 곡선에 대한 높은 확신을 갖고 5년 지평으로 투자합니다.",
    styleTagsEn: ["Disruptive Tech", "Genomics", "AI", "Exponential Growth"],
    styleTagsKo: ["혁신 기술", "유전체학", "AI", "지수적 성장"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 38.4, color: "#8b5cf6" },
      { sector: "Healthcare / Genomics", weight: 22.1, color: "#ef4444" },
      { sector: "Consumer / EV", weight: 18.7, color: "#f59e0b" },
      { sector: "Crypto / Fintech", weight: 14.2, color: "#f97316" },
      { sector: "Other", weight: 6.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "TSLA", company: "Tesla Inc.", sector: "Consumer", shares: 8200000, weight: 8.4, change: "Held", changePct: 0, whyTheyBoughtEn: "ARK sees Tesla not as a car company but as an AI and robotics platform. Full Self-Driving, Optimus robot, and Dojo supercomputer represent trillion-dollar opportunities.", whyTheyBoughtKo: "ARK는 테슬라를 자동차 회사가 아닌 AI와 로봇 플랫폼으로 봅니다. 완전 자율주행, 옵티머스 로봇, 도조 슈퍼컴퓨터는 수조 달러 기회를 대표합니다." },
      { ticker: "ROKU", company: "Roku Inc.", sector: "Technology", shares: 18000000, weight: 7.8, change: "Sold", changePct: -12.4, whyTheyBoughtEn: "Connected TV platform as the dominant OS for smart TVs. ARK sees streaming ad revenue transitioning from linear TV, giving Roku massive monetization leverage.", whyTheyBoughtKo: "스마트 TV의 지배적 OS로서의 커넥티드 TV 플랫폼입니다. ARK는 선형 TV에서 스트리밍 광고 수익의 전환을 보며 로쿠에 막대한 수익화 레버리지를 제공합니다." },
      { ticker: "CRSP", company: "CRISPR Therapeutics", sector: "Healthcare", shares: 12000000, weight: 6.9, change: "Held", changePct: 0, whyTheyBoughtEn: "Gene-editing platform that could cure genetic diseases permanently. First FDA-approved CRISPR therapy validates the technology, opening multi-trillion dollar healthcare market.", whyTheyBoughtKo: "유전 질환을 영구적으로 치료할 수 있는 유전자 편집 플랫폼입니다. 최초 FDA 승인 CRISPR 치료법이 기술을 검증하며 수조 달러 헬스케어 시장을 엽니다." },
      { ticker: "COIN", company: "Coinbase", sector: "Financials", shares: 8400000, weight: 8.2, change: "Bought", changePct: 18.4, whyTheyBoughtEn: "ARK views Coinbase as the regulated gateway to the crypto asset class — a beneficiary of Bitcoin ETF approvals and institutional adoption of digital assets.", whyTheyBoughtKo: "ARK는 코인베이스를 암호자산 클래스로의 규제된 진입 통로로 봅니다 — 비트코인 ETF 승인과 기관의 디지털 자산 채택의 수혜자입니다." },
    ],
  },

  // ─── MACRO ──────────────────────────────────────────────────────────────────
  {
    id: "dalio",
    name: "Ray Dalio",
    firm: "Bridgewater Associates",
    country: "US",
    aum: 124,
    aumUnit: "B",
    initials: "RD",
    avatarColor: "#7c3aed",
    category: "macro",
    biographyEn: "Ray Dalio founded Bridgewater Associates in his New York apartment in 1975. It became the world's largest hedge fund. His 'All Weather' portfolio and 'radical transparency' culture revolutionized hedge fund management.",
    biographyKo: "레이 달리오는 1975년 뉴욕 아파트에서 브리지워터 어소시에이츠를 창립했습니다. 세계 최대 헤지펀드로 성장했습니다. '올웨더' 포트폴리오와 '극단적 투명성' 문화가 헤지펀드 운용을 혁신했습니다.",
    styleEn: "Global macro investing with a focus on 'All Weather' portfolio construction. Risk parity — balancing risk across economic environments rather than capital allocation.",
    styleKo: "모든 경제 환경에서 탄력적인 '올웨더' 포트폴리오 구성에 초점을 맞춘 글로벌 매크로 투자. 리스크 패리티 — 자본이 아닌 위험을 경제 환경 전반에서 균형 있게 배분합니다.",
    styleTagsEn: ["Global Macro", "Risk Parity", "All Weather", "Diversification"],
    styleTagsKo: ["글로벌 매크로", "리스크 패리티", "올웨더", "분산투자"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "ETFs / Index", weight: 42.3, color: "#3b82f6" },
      { sector: "Emerging Markets", weight: 18.7, color: "#f59e0b" },
      { sector: "Consumer Staples", weight: 9.8, color: "#10b981" },
      { sector: "Healthcare", weight: 9.4, color: "#ef4444" },
      { sector: "Financials", weight: 8.2, color: "#8b5cf6" },
      { sector: "Gold / Commodities", weight: 7.6, color: "#f97316" },
      { sector: "Other", weight: 4.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "SPY", company: "SPDR S&P 500 ETF", sector: "ETFs / Index", shares: 10200000, weight: 18.4, change: "Bought", changePct: 8.2, whyTheyBoughtEn: "Core broad market exposure. In Dalio's All Weather portfolio, US equities represent one leg of the risk parity framework — performing well in growth environments.", whyTheyBoughtKo: "핵심 광범위 시장 노출. 달리오의 올웨더 포트폴리오에서 미국 주식은 리스크 패리티 프레임워크의 한 축 — 성장 환경에서 좋은 성과를 냅니다." },
      { ticker: "EEM", company: "iShares Emerging Markets ETF", sector: "Emerging Markets", shares: 19800000, weight: 14.2, change: "Bought", changePct: 12.1, whyTheyBoughtEn: "Dalio is bullish on emerging markets especially China and India. EEM provides exposure to these growth economies with their younger populations and rising middle classes.", whyTheyBoughtKo: "달리오는 특히 중국과 인도의 신흥시장에 대해 강세입니다. EEM은 더 젊은 인구와 증가하는 중산층을 가진 성장 경제에 대한 노출을 제공합니다." },
      { ticker: "GLD", company: "SPDR Gold Shares ETF", sector: "Gold / Commodities", shares: 5600000, weight: 7.6, change: "Held", changePct: 0, whyTheyBoughtEn: "Gold is Dalio's inflation and currency debasement hedge. In his framework, gold performs when fiat currencies lose purchasing power. He says 'Cash is trash.'", whyTheyBoughtKo: "금은 달리오의 인플레이션 및 통화 가치 하락 헤지입니다. '현금은 쓰레기다'라는 유명한 말을 남겼으며 금융 시스템 외부의 가치 저장 수단으로서 금을 지지합니다." },
      { ticker: "PG", company: "Procter & Gamble", sector: "Consumer Staples", shares: 4800000, weight: 3.8, change: "Held", changePct: 0, whyTheyBoughtEn: "Consumer staples perform well during economic downturns. P&G is a defensive stalwart with brands people buy regardless of economic conditions.", whyTheyBoughtKo: "소비자 필수품은 경기 침체 시 좋은 성과를 냅니다. P&G는 경제 상황에 관계없이 사람들이 구매하는 브랜드를 보유한 방어적 기업입니다." },
    ],
  },

  {
    id: "soros",
    name: "George Soros",
    firm: "Soros Fund Management",
    country: "US",
    aum: 25,
    aumUnit: "B",
    initials: "GS",
    avatarColor: "#b45309",
    category: "macro",
    biographyEn: "George Soros is famous for 'Breaking the Bank of England' in 1992 — a single trade that made $1 billion in profit. His theory of reflexivity underpins his unique approach to markets.",
    biographyKo: "조지 소로스는 1992년 '영국 중앙은행 공략'으로 유명합니다 — 단일 거래로 10억 달러 이익을 냈습니다. 그의 반사성 이론이 시장에 대한 독특한 접근법을 뒷받침합니다.",
    styleEn: "Macro investing based on 'reflexivity' — markets and fundamentals influence each other in feedback loops. Identifies mispricings and takes massive leveraged positions to exploit them.",
    styleKo: "시장과 펀더멘털이 피드백 루프에서 서로 영향을 미치는 '반사성'에 기반한 매크로 투자. 가격 오류를 식별하고 이를 활용하기 위해 대규모 레버리지 포지션을 취합니다.",
    styleTagsEn: ["Global Macro", "Reflexivity", "Currency", "Leveraged Bets"],
    styleTagsKo: ["글로벌 매크로", "반사성", "통화", "레버리지 베팅"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 28.4, color: "#8b5cf6" },
      { sector: "Consumer", weight: 22.1, color: "#f59e0b" },
      { sector: "Healthcare", weight: 18.3, color: "#ef4444" },
      { sector: "Energy / Materials", weight: 16.4, color: "#f97316" },
      { sector: "Financials", weight: 14.8, color: "#3b82f6" },
    ],
    holdings: [
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 3200000, weight: 12.4, change: "New", changePct: null, whyTheyBoughtEn: "Soros sees NVIDIA's AI dominance as a reflexive phenomenon — AI hype drives GPU demand, GPU demand confirms AI narrative, creating self-reinforcing momentum.", whyTheyBoughtKo: "소로스는 엔비디아의 AI 지배력을 반사적 현상으로 봅니다 — AI 기대가 GPU 수요를 이끌고, GPU 수요가 AI 내러티브를 확인하며 자기 강화 모멘텀을 만듭니다." },
      { ticker: "LLY", company: "Eli Lilly & Co.", sector: "Healthcare", shares: 1800000, weight: 14.2, change: "Bought", changePct: 28.4, whyTheyBoughtEn: "Eli Lilly's GLP-1 drugs (Mounjaro, Zepbound) are reshaping obesity treatment globally. Soros sees a generational pharmaceutical opportunity as obesity becomes a treatable disease.", whyTheyBoughtKo: "일라이 릴리의 GLP-1 약물(마운자로, 젭바운드)이 전 세계 비만 치료를 재편하고 있습니다. 비만이 치료 가능한 질병이 되면서 소로스는 세대적 제약 기회를 봅니다." },
      { ticker: "BABA", company: "Alibaba Group", sector: "Technology", shares: 9400000, weight: 8.7, change: "Sold", changePct: -22.4, whyTheyBoughtEn: "Contrarian bet on China normalization and regulatory easing. Alibaba trades at fraction of US peer valuations, creating asymmetric upside if geopolitical tension eases.", whyTheyBoughtKo: "중국 정상화와 규제 완화에 대한 역발상 베팅입니다. 알리바바는 미국 동종 기업 밸류에이션의 일부에 거래되며 지정학적 긴장 완화 시 비대칭 상승 잠재력이 있습니다." },
    ],
  },

  {
    id: "druckenmiller",
    name: "Stanley Druckenmiller",
    firm: "Duquesne Family Office",
    country: "US",
    aum: 6.9,
    aumUnit: "B",
    initials: "SD",
    avatarColor: "#0f766e",
    category: "macro",
    biographyEn: "Stanley Druckenmiller worked alongside George Soros on the famous 'Breaking the Bank of England' trade. He ran Duquesne Capital for 30 years with an unparalleled 30%+ average annual return before converting to a family office.",
    biographyKo: "스탠리 드러켄밀러는 유명한 '영국 중앙은행 공략' 거래에서 조지 소로스와 함께 일했습니다. 가족사무소로 전환하기 전 30년간 30% 이상의 연평균 수익률로 듀케인 캐피털을 운용했습니다.",
    styleEn: "Top-down macro approach focused on liquidity conditions, central bank policy, and currency flows. Takes highly concentrated bets when conviction is high, runs tight stops on mistakes.",
    styleKo: "유동성 조건, 중앙은행 정책, 통화 흐름에 집중하는 하향식 매크로 접근법. 확신이 높을 때 매우 집중적인 베팅을 취하고 실수에 대해 손실 한도를 엄격히 적용합니다.",
    styleTagsEn: ["Global Macro", "Liquidity Focus", "Concentrated Bets", "Disciplined Stops"],
    styleTagsKo: ["글로벌 매크로", "유동성 집중", "집중 베팅", "엄격한 손절"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 44.2, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 22.8, color: "#ef4444" },
      { sector: "Consumer", weight: 18.4, color: "#f59e0b" },
      { sector: "Financials", weight: 14.6, color: "#3b82f6" },
    ],
    holdings: [
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 8400000, weight: 28.4, change: "Bought", changePct: 42.1, whyTheyBoughtEn: "Druckenmiller's largest position. He says NVIDIA is the 'picks and shovels' of the AI gold rush — everyone needs their GPUs, creating an unprecedented monopoly in AI infrastructure.", whyTheyBoughtKo: "드러켄밀러의 최대 포지션입니다. 엔비디아를 AI 골드러시의 '곡괭이와 삽'으로 부릅니다 — 모두가 GPU를 필요로 하며 AI 인프라에서 전례 없는 독점을 만듭니다." },
      { ticker: "LLY", company: "Eli Lilly & Co.", sector: "Healthcare", shares: 3200000, weight: 18.2, change: "Bought", changePct: 24.8, whyTheyBoughtEn: "GLP-1 obesity drugs represent the biggest pharmaceutical breakthrough in decades. Druckenmiller sees Eli Lilly as having an unassailable multi-year competitive lead.", whyTheyBoughtKo: "GLP-1 비만 치료제는 수십 년 만에 가장 큰 제약 혁신입니다. 드러켄밀러는 일라이 릴리가 수년간 넘볼 수 없는 경쟁 우위를 가지고 있다고 봅니다." },
      { ticker: "VST", company: "Vistra Corp", sector: "Energy", shares: 12400000, weight: 14.6, change: "New", changePct: null, whyTheyBoughtEn: "Power generation company benefiting from AI data center electricity demand explosion. Nuclear and natural gas assets make Vistra a critical infrastructure play for the AI era.", whyTheyBoughtKo: "AI 데이터센터 전력 수요 폭발의 혜택을 받는 발전 회사입니다. 원자력 및 천연가스 자산이 비스타를 AI 시대의 핵심 인프라 투자처로 만듭니다." },
    ],
  },

  // ─── HEDGE / MULTI-STRATEGY ─────────────────────────────────────────────────
  {
    id: "griffin",
    name: "Ken Griffin",
    firm: "Citadel LLC",
    country: "US",
    aum: 62,
    aumUnit: "B",
    initials: "KG",
    avatarColor: "#0369a1",
    category: "hedge",
    biographyEn: "Ken Griffin founded Citadel in 1990 from his Harvard dorm room. Citadel is now one of the world's most profitable hedge funds, generating over $74 billion in gains since inception — more than any other hedge fund in history.",
    biographyKo: "켄 그리핀은 1990년 하버드 기숙사 방에서 시타델을 설립했습니다. 시타델은 이제 설립 이래 740억 달러 이상의 수익을 창출한 세계에서 가장 수익성 높은 헤지펀드 중 하나입니다.",
    styleEn: "Multi-strategy quantitative investing combining fundamental analysis, statistical arbitrage, market making, and fixed income strategies across all asset classes globally.",
    styleKo: "전 세계 모든 자산 클래스에서 기본 분석, 통계적 차익거래, 시장 조성, 고정 수익 전략을 결합한 다전략 퀀트 투자.",
    styleTagsEn: ["Multi-Strategy", "Quantitative", "Statistical Arb", "Market Making"],
    styleTagsKo: ["다전략", "퀀트", "통계적 차익거래", "시장 조성"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 22.4, color: "#8b5cf6" },
      { sector: "Financials", weight: 18.7, color: "#3b82f6" },
      { sector: "Healthcare", weight: 16.3, color: "#ef4444" },
      { sector: "Consumer", weight: 14.8, color: "#f59e0b" },
      { sector: "Industrials", weight: 13.2, color: "#10b981" },
      { sector: "Other", weight: 14.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 14000000, weight: 8.4, change: "Bought", changePct: 12.3, whyTheyBoughtEn: "Citadel's quant models identified NVIDIA's accelerating earnings revisions before consensus. AI compute demand is structurally undercounted in current forecasts.", whyTheyBoughtKo: "시타델의 퀀트 모델이 컨센서스 전에 엔비디아의 실적 추정치 상향을 식별했습니다. AI 컴퓨팅 수요는 현재 전망에서 구조적으로 과소 평가되어 있습니다." },
      { ticker: "AMZN", company: "Amazon.com", sector: "Technology", shares: 22000000, weight: 7.8, change: "Held", changePct: 0, whyTheyBoughtEn: "Amazon's AWS cloud dominance and advertising business are structural compounders. Citadel's fundamental analysts see margin expansion driving earnings acceleration.", whyTheyBoughtKo: "아마존의 AWS 클라우드 지배력과 광고 사업이 구조적 복리 성장을 보입니다. 시타델의 기본 분석가들은 마진 확대가 실적 가속을 이끈다고 봅니다." },
      { ticker: "LLY", company: "Eli Lilly & Co.", sector: "Healthcare", shares: 5800000, weight: 9.2, change: "Bought", changePct: 18.4, whyTheyBoughtEn: "GLP-1 pipeline has a decade of growth ahead. Citadel's healthcare specialists estimate the total addressable market for obesity drugs exceeds $150 billion annually.", whyTheyBoughtKo: "GLP-1 파이프라인은 10년의 성장 가능성이 있습니다. 시타델의 헬스케어 전문가들은 비만 치료제의 연간 전체 잠재 시장이 1,500억 달러를 초과한다고 추정합니다." },
    ],
  },

  {
    id: "englander",
    name: "Izzy Englander",
    firm: "Millennium Management",
    country: "US",
    aum: 66,
    aumUnit: "B",
    initials: "IE",
    avatarColor: "#7e22ce",
    category: "hedge",
    biographyEn: "Israel 'Izzy' Englander founded Millennium Management in 1989 with $35 million. It grew to become one of the world's largest multi-strategy hedge funds. Millennium has never had a losing year since inception.",
    biographyKo: "이즈라엘 '이지' 잉글랜더는 1989년 3,500만 달러로 밀레니엄 매니지먼트를 설립했습니다. 세계 최대 다전략 헤지펀드 중 하나로 성장했습니다. 밀레니엄은 설립 이래 손실 연도가 없습니다.",
    styleEn: "Multi-strategy approach with hundreds of independent portfolio managers each running their own book. Extreme diversification and risk management ensure consistent returns in all markets.",
    styleKo: "각자의 포트폴리오를 운용하는 수백 명의 독립 포트폴리오 매니저를 통한 다전략 접근법. 극단적 분산투자와 위험 관리가 모든 시장에서 일관된 수익을 보장합니다.",
    styleTagsEn: ["Multi-Strategy", "Pod Structure", "Risk Management", "Consistent Returns"],
    styleTagsKo: ["다전략", "팟 구조", "위험 관리", "일관된 수익"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 24.2, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 20.1, color: "#ef4444" },
      { sector: "Financials", weight: 17.8, color: "#3b82f6" },
      { sector: "Consumer", weight: 15.4, color: "#f59e0b" },
      { sector: "Industrials", weight: 12.3, color: "#10b981" },
      { sector: "Other", weight: 10.2, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 18000000, weight: 6.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Multiple Millennium PMs independently converge on Microsoft as the AI infrastructure winner. Azure growth, Copilot monetization, and gaming all contribute to earnings visibility.", whyTheyBoughtKo: "여러 밀레니엄 PM들이 독립적으로 마이크로소프트를 AI 인프라 승자로 수렴합니다. Azure 성장, 코파일럿 수익화, 게이밍 모두 실적 가시성에 기여합니다." },
      { ticker: "UNH", company: "UnitedHealth Group", sector: "Healthcare", shares: 4800000, weight: 8.2, change: "Bought", changePct: 8.7, whyTheyBoughtEn: "Dominant managed care organization with consistent earnings growth. Healthcare spending is non-discretionary and UNH's scale provides insurmountable competitive advantages.", whyTheyBoughtKo: "일관된 실적 성장을 보이는 지배적 관리의료 기관입니다. 의료비 지출은 필수적이며 UNH의 규모는 극복할 수 없는 경쟁 우위를 제공합니다." },
      { ticker: "GOOGL", company: "Alphabet Inc.", sector: "Technology", shares: 12000000, weight: 7.1, change: "Held", changePct: 0, whyTheyBoughtEn: "Millennium's PMs favor Alphabet for its search dominance and underappreciated AI assets. DeepMind research positions Google ahead of peers in frontier AI.", whyTheyBoughtKo: "밀레니엄의 PM들은 검색 지배력과 저평가된 AI 자산으로 알파벳을 선호합니다. 딥마인드 연구가 구글을 프론티어 AI에서 동종 업체보다 앞서게 합니다." },
    ],
  },

  {
    id: "burry",
    name: "Michael Burry",
    firm: "Scion Asset Management",
    country: "US",
    aum: 0.36,
    aumUnit: "B",
    initials: "MB",
    avatarColor: "#b91c1c",
    category: "hedge",
    biographyEn: "Michael Burry became famous for his massive short bet against the US housing market before the 2008 financial crisis — immortalized in 'The Big Short.' A trained physician who turned to investing.",
    biographyKo: "마이클 버리는 2008년 금융위기 전 미국 주택 시장에 대한 대규모 공매도 베팅으로 유명해졌습니다 — '빅쇼트'에 불멸의 이야기로 기록되었습니다. 의사 출신의 투자자입니다.",
    styleEn: "Deep value contrarian investing. Finds assets priced well below intrinsic value in unpopular or misunderstood sectors. Known for macro short bets and concentrated stock picking.",
    styleKo: "심층 가치 역발상 투자. 비인기적이거나 잘못 이해된 섹터에서 내재 가치보다 훨씬 낮게 가격이 책정된 자산을 찾습니다. 매크로 공매도 베팅과 집중적 종목 선정으로 유명합니다.",
    styleTagsEn: ["Deep Value", "Contrarian", "Concentrated", "Short Selling"],
    styleTagsKo: ["심층 가치", "역발상", "집중 투자", "공매도"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 34.8, color: "#8b5cf6" },
      { sector: "Consumer Discretionary", weight: 28.2, color: "#f59e0b" },
      { sector: "Financials", weight: 19.6, color: "#3b82f6" },
      { sector: "Healthcare", weight: 11.4, color: "#ef4444" },
      { sector: "Other", weight: 6.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "BABA", company: "Alibaba Group", sector: "Technology", shares: 250000, weight: 22.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Burry sees Alibaba deeply undervalued relative to its earnings power — trading at low single-digit P/E despite massive cash flows. Chinese regulatory pressure created a generational opportunity.", whyTheyBoughtKo: "버리는 알리바바가 수익 창출 능력 대비 심각하게 저평가되어 있다고 봅니다 — 거대한 현금 흐름에도 불구하고 한 자리 수 P/E에 거래됩니다." },
      { ticker: "JD", company: "JD.com Inc.", sector: "Consumer Discretionary", shares: 500000, weight: 14.8, change: "Bought", changePct: 28.3, whyTheyBoughtEn: "JD.com operates its own logistics network, giving it structural cost advantages. At Burry's entry price, it traded at a fraction of its logistics infrastructure value alone.", whyTheyBoughtKo: "JD닷컴은 자체 물류 네트워크를 운영하여 구조적 비용 우위를 갖습니다. 버리의 진입가에서 물류 인프라 가치만의 일부에 거래되었습니다." },
      { ticker: "HCA", company: "HCA Healthcare", sector: "Healthcare", shares: 180000, weight: 11.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Largest US for-profit hospital chain with pricing power and scale advantages. Healthcare demand is inelastic, and HCA benefits from aging US population demographics.", whyTheyBoughtKo: "가격 결정력과 규모의 경제를 갖춘 미국 최대 영리 병원 체인입니다. 헬스케어 수요는 비탄력적이며 HCA는 미국 인구 고령화 트렌드의 혜택을 받습니다." },
      { ticker: "GEO", company: "GEO Group Inc.", sector: "Financials", shares: 1200000, weight: 9.6, change: "Bought", changePct: 15.7, whyTheyBoughtEn: "Private prison operator with government contracts providing stable recurring revenue. Heavily stigmatized by ESG concerns, driving the stock to what Burry views as severely undervalued levels.", whyTheyBoughtKo: "정부 계약으로 안정적인 반복 수익을 제공하는 민간 교도소 운영업체입니다. ESG 우려로 크게 낙인찍혀 주가가 버리가 심각하게 저평가된 수준으로 내려갔습니다." },
    ],
  },

  {
    id: "simons",
    name: "Jim Simons",
    firm: "Renaissance Technologies",
    country: "US",
    aum: 55,
    aumUnit: "B",
    initials: "JS",
    avatarColor: "#0e7490",
    category: "hedge",
    biographyEn: "Jim Simons was a mathematics professor and codebreaker before founding Renaissance Technologies in 1982. His Medallion Fund returned 66% annually before fees for 30 years — the greatest trading record in history.",
    biographyKo: "짐 사이먼스는 1982년 르네상스 테크놀로지스를 설립하기 전 수학 교수이자 암호 해독가였습니다. 그의 메달리온 펀드는 30년간 수수료 전 연 66%를 기록했습니다 — 역사상 가장 위대한 거래 기록입니다.",
    styleEn: "Pure quantitative investing using mathematical models, pattern recognition, and statistical signals. No fundamental analysis — only data, signals, and algorithms.",
    styleKo: "수학적 모델, 패턴 인식, 통계적 신호를 사용한 순수 퀀트 투자. 기본 분석 없음 — 오직 데이터, 신호, 알고리즘만 사용합니다.",
    styleTagsEn: ["Pure Quant", "Algorithmic", "Pattern Recognition", "Mathematical Models"],
    styleTagsKo: ["순수 퀀트", "알고리즘", "패턴 인식", "수학적 모델"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 26.3, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 19.8, color: "#ef4444" },
      { sector: "Consumer", weight: 16.4, color: "#f59e0b" },
      { sector: "Industrials", weight: 14.2, color: "#10b981" },
      { sector: "Financials", weight: 12.7, color: "#3b82f6" },
      { sector: "Other", weight: 10.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 6200000, weight: 8.4, change: "Bought", changePct: 22.4, whyTheyBoughtEn: "Renaissance's models detected momentum signals in NVIDIA months before Wall Street upgraded targets. Statistical patterns in GPU demand data pointed to earnings beats.", whyTheyBoughtKo: "르네상스의 모델은 월스트리트 목표 주가 상향 수 개월 전 엔비디아의 모멘텀 신호를 감지했습니다. GPU 수요 데이터의 통계적 패턴이 실적 서프라이즈를 가리켰습니다." },
      { ticker: "UNH", company: "UnitedHealth Group", sector: "Healthcare", shares: 3800000, weight: 7.2, change: "Held", changePct: 0, whyTheyBoughtEn: "Renaissance models favor UNH for its consistent earnings beat rate and low volatility profile. High Sharpe ratio and predictable cash flows match Renaissance's return optimization.", whyTheyBoughtKo: "르네상스 모델은 일관된 실적 초과 달성률과 낮은 변동성으로 UNH를 선호합니다. 높은 샤프 비율과 예측 가능한 현금 흐름이 르네상스의 수익 최적화와 일치합니다." },
    ],
  },

  {
    id: "cohen",
    name: "Steve Cohen",
    firm: "Point72 Asset Management",
    country: "US",
    aum: 36,
    aumUnit: "B",
    initials: "SC",
    avatarColor: "#be185d",
    category: "hedge",
    biographyEn: "Steve Cohen built SAC Capital into one of the most profitable hedge funds ever. After legal issues, he founded Point72, which now manages $35B+. He is also the owner of the New York Mets.",
    biographyKo: "스티브 코헨은 SAC 캐피털을 역대 가장 수익성 높은 헤지펀드 중 하나로 키웠습니다. 법적 문제 이후 포인트72를 설립했으며 현재 350억 달러 이상을 운용합니다. 뉴욕 메츠의 오너이기도 합니다.",
    styleEn: "Information-edge investing with exceptionally fast idea generation. Point72's analysts generate hundreds of ideas monthly. Focuses on near-term catalysts and earnings revision cycles.",
    styleKo: "매우 빠른 아이디어 생성과 정보 우위 투자. 포인트72의 분석가들은 매월 수백 개의 아이디어를 생성합니다. 단기 촉매제와 실적 추정치 개정 사이클에 집중합니다.",
    styleTagsEn: ["Information Edge", "Catalyst-Driven", "Short-Term", "High Turnover"],
    styleTagsKo: ["정보 우위", "촉매 중심", "단기", "높은 회전율"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 28.4, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 22.1, color: "#ef4444" },
      { sector: "Consumer", weight: 18.7, color: "#f59e0b" },
      { sector: "Financials", weight: 16.3, color: "#3b82f6" },
      { sector: "Other", weight: 14.5, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "LLY", company: "Eli Lilly & Co.", sector: "Healthcare", shares: 4200000, weight: 12.4, change: "Bought", changePct: 18.2, whyTheyBoughtEn: "Point72's healthcare analysts identified Eli Lilly's GLP-1 competitive moat early. Mounjaro's superior efficacy data versus competitors supports sustained market share gains.", whyTheyBoughtKo: "포인트72의 헬스케어 분석가들은 일라이 릴리의 GLP-1 경쟁 해자를 일찍 식별했습니다. 마운자로의 경쟁사 대비 우수한 효능 데이터가 지속적인 시장 점유율 확대를 지지합니다." },
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 8800000, weight: 9.7, change: "Held", changePct: 0, whyTheyBoughtEn: "Cohen's team sees Microsoft Copilot adoption surprising consensus. Enterprise AI monetization is in the early innings with vast upsell opportunity across Office 365 base.", whyTheyBoughtKo: "코헨의 팀은 마이크로소프트 코파일럿 채택이 컨센서스를 놀라게 한다고 봅니다. 기업 AI 수익화는 오피스 365 기반 전반에 걸쳐 방대한 업셀 기회로 초기 단계에 있습니다." },
    ],
  },

  // ─── ACTIVIST ───────────────────────────────────────────────────────────────
  {
    id: "ackman",
    name: "Bill Ackman",
    firm: "Pershing Square Capital",
    country: "US",
    aum: 18,
    aumUnit: "B",
    initials: "BA",
    avatarColor: "#0c4a6e",
    category: "activist",
    biographyEn: "Bill Ackman is one of the most prominent activist hedge fund managers. Known for both spectacular wins (Chipotle, Howard Hughes) and famous failures (Herbalife short, Valeant). He raised a $4B SPAC in 2020.",
    biographyKo: "빌 애크먼은 가장 유명한 행동주의 헤지펀드 매니저 중 한 명입니다. 화려한 성공(치폴레, 하워드 휴즈)과 유명한 실패(허바라이프 공매도, 발리언트) 모두로 유명합니다.",
    styleEn: "Concentrated activist investing — takes large stakes in a small number of companies and publicly advocates for change. Typically holds 6-10 positions with significant influence on management.",
    styleKo: "집중 행동주의 투자 — 소수의 회사에 대규모 지분을 취득하고 공개적으로 변화를 주창합니다. 경영진에 상당한 영향력을 가진 6-10개 포지션을 보유합니다.",
    styleTagsEn: ["Activist", "Concentrated", "Public Advocacy", "Value Catalyst"],
    styleTagsKo: ["행동주의", "집중 투자", "공개 주창", "가치 촉매"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Consumer", weight: 32.4, color: "#f59e0b" },
      { sector: "Financials", weight: 24.8, color: "#3b82f6" },
      { sector: "Technology", weight: 22.1, color: "#8b5cf6" },
      { sector: "Real Estate", weight: 14.3, color: "#10b981" },
      { sector: "Other", weight: 6.4, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "CMG", company: "Chipotle Mexican Grill", sector: "Consumer", shares: 2200000, weight: 22.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Ackman bought Chipotle at trough in 2016 after food safety crisis and pushed for a new CEO (Brian Niccol). His thesis was that a great brand with great execution will recover — it 10x'd.", whyTheyBoughtKo: "애크먼은 2016년 식품 안전 위기 후 저점에 치폴레를 매수하고 새 CEO(브라이언 니콜) 영입을 주도했습니다. 훌륭한 실행력을 갖춘 위대한 브랜드는 회복한다는 논거로 10배 상승했습니다." },
      { ticker: "GOOG", company: "Alphabet Inc.", sector: "Technology", shares: 7200000, weight: 18.7, change: "New", changePct: null, whyTheyBoughtEn: "Ackman sees Alphabet's AI capabilities deeply undervalued. DeepMind breakthroughs, Search dominance, and YouTube monetization provide multiple paths to value creation.", whyTheyBoughtKo: "애크먼은 알파벳의 AI 역량이 심각하게 저평가되어 있다고 봅니다. 딥마인드 혁신, 검색 지배력, 유튜브 수익화가 가치 창출의 다양한 경로를 제공합니다." },
      { ticker: "HHH", company: "Howard Hughes Holdings", sector: "Real Estate", shares: 8400000, weight: 14.3, change: "Held", changePct: 0, whyTheyBoughtEn: "Master-planned community developer with irreplaceable land assets. Ackman is the chairman and sees HHH's NAV significantly above the market price, with long-term development optionality.", whyTheyBoughtKo: "대체 불가능한 토지 자산을 가진 계획 커뮤니티 개발업체입니다. 애크먼은 의장으로서 장기 개발 옵션성과 함께 HHH의 순자산가치가 시장가를 크게 상회한다고 봅니다." },
    ],
  },

  {
    id: "singer",
    name: "Paul Singer",
    firm: "Elliott Management",
    country: "US",
    aum: 73,
    aumUnit: "B",
    initials: "PS",
    avatarColor: "#7f1d1d",
    category: "activist",
    biographyEn: "Paul Singer founded Elliott Management in 1977 with $1.3 million. Elliott is known as one of the most aggressive and successful activist hedge funds, taking on entire countries (Argentina) and corporate giants.",
    biographyKo: "폴 싱어는 1977년 130만 달러로 엘리엇 매니지먼트를 설립했습니다. 엘리엇은 아르헨티나 같은 국가와 대기업을 상대로 가장 공격적이고 성공적인 행동주의 헤지펀드 중 하나로 알려져 있습니다.",
    styleEn: "Aggressive activist investing with expertise in distressed debt, corporate restructuring, and event-driven strategies. Not afraid to take legal action or engage in public battles.",
    styleKo: "부실 채권, 기업 구조조정, 이벤트 중심 전략에 전문성을 가진 공격적인 행동주의 투자. 법적 조치나 공개 전쟁을 두려워하지 않습니다.",
    styleTagsEn: ["Activist", "Distressed Debt", "Event-Driven", "Aggressive Tactics"],
    styleTagsKo: ["행동주의", "부실 채권", "이벤트 중심", "공격적 전술"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 28.4, color: "#8b5cf6" },
      { sector: "Industrials", weight: 24.2, color: "#f59e0b" },
      { sector: "Energy", weight: 18.7, color: "#ef4444" },
      { sector: "Financials", weight: 16.3, color: "#3b82f6" },
      { sector: "Other", weight: 12.4, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "PINS", company: "Pinterest", sector: "Technology", shares: 18000000, weight: 12.4, change: "New", changePct: null, whyTheyBoughtEn: "Elliott took a 9% stake and pushed Pinterest to maximize its underutilized ad potential and consider strategic alternatives. The platform's demographic data is a gold mine for advertisers.", whyTheyBoughtKo: "엘리엇은 9% 지분을 취득하고 핀터레스트에 저활용된 광고 잠재력 극대화와 전략적 대안 검토를 촉구했습니다. 플랫폼의 인구통계 데이터는 광고주에게 금광입니다." },
      { ticker: "TXN", company: "Texas Instruments", sector: "Technology", shares: 8400000, weight: 11.8, change: "Bought", changePct: 14.2, whyTheyBoughtEn: "Elliott pushed for improved capital allocation and higher returns at TI. The analog chip company has unmatched manufacturing scale with 40% market share in key segments.", whyTheyBoughtKo: "엘리엇은 TI에 자본 배분 개선과 더 높은 수익률을 촉구했습니다. 아날로그 칩 회사는 핵심 부문에서 40% 시장 점유율로 타의 추종을 불허하는 제조 규모를 보유합니다." },
    ],
  },

  {
    id: "loeb",
    name: "Dan Loeb",
    firm: "Third Point LLC",
    country: "US",
    aum: 12,
    aumUnit: "B",
    initials: "DL",
    avatarColor: "#166534",
    category: "activist",
    biographyEn: "Dan Loeb founded Third Point in 1995 and is famous for his acerbic public letters to management teams. He has taken activist positions at Yahoo, Sony, Nestle, Disney, and many others.",
    biographyKo: "댄 로브는 1995년 서드포인트를 설립했으며 경영진에게 신랄한 공개 서한을 보내는 것으로 유명합니다. 야후, 소니, 네슬레, 디즈니 등 많은 기업에서 행동주의 포지션을 취했습니다.",
    styleEn: "Event-driven activist investing focusing on catalysts: management changes, corporate restructuring, spin-offs, and M&A. Also maintains a diversified long/short book alongside activist positions.",
    styleKo: "경영진 교체, 기업 구조조정, 분할, M&A 등 촉매에 집중하는 이벤트 중심 행동주의 투자. 행동주의 포지션과 함께 분산된 롱/숏 포지션도 유지합니다.",
    styleTagsEn: ["Activist", "Event-Driven", "Spin-offs", "Management Change"],
    styleTagsKo: ["행동주의", "이벤트 중심", "기업 분할", "경영진 교체"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 32.4, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 24.8, color: "#ef4444" },
      { sector: "Consumer", weight: 18.2, color: "#f59e0b" },
      { sector: "Financials", weight: 14.7, color: "#3b82f6" },
      { sector: "Other", weight: 9.9, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "PFE", company: "Pfizer Inc.", sector: "Healthcare", shares: 42000000, weight: 14.8, change: "New", changePct: null, whyTheyBoughtEn: "Loeb sees Pfizer's pipeline deeply discounted after COVID vaccine revenue decline. With a pipeline of 80+ programs and trading at historical low multiples, the risk/reward is asymmetric.", whyTheyBoughtKo: "로브는 코로나 백신 수익 감소 후 화이자의 파이프라인이 심각하게 할인되어 있다고 봅니다. 80개 이상의 프로그램 파이프라인과 역사적 저밸류에이션으로 위험/보상이 비대칭적입니다." },
      { ticker: "AMZN", company: "Amazon.com", sector: "Technology", shares: 11000000, weight: 12.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Third Point sees Amazon's retail profitability transformation and AWS reaccelerating as the two major catalysts. Advertising is an underappreciated third engine of growth.", whyTheyBoughtKo: "서드포인트는 아마존의 소매 수익성 전환과 AWS 재가속을 두 가지 주요 촉매로 봅니다. 광고는 과소 평가된 세 번째 성장 동력입니다." },
    ],
  },

  // ─── SOVEREIGN / PENSION ────────────────────────────────────────────────────
  {
    id: "nps",
    name: "국민연금공단 (NPS)",
    firm: "National Pension Service",
    country: "KR",
    aum: 1100,
    aumUnit: "T₩",
    initials: "NP",
    avatarColor: "#059669",
    category: "sovereign",
    biographyEn: "South Korea's National Pension Service manages ₩1,100+ trillion ($850B+) and covers 22M+ subscribers. It is one of the world's largest pension funds and its decisions move Korean markets.",
    biographyKo: "한국 국민연금공단은 1,100조 원(약 8,500억 달러) 이상을 운용하고 2,200만 명 이상의 가입자를 보유합니다. 세계 최대 연금 기금 중 하나로 투자 결정이 한국 시장을 움직입니다.",
    styleEn: "Long-term institutional diversification across domestic equities, foreign equities, bonds, and alternative assets. Acts as a 'market stabilizer' during crashes.",
    styleKo: "국내 주식, 해외 주식, 채권, 대체 자산에 걸친 장기 기관 분산투자. 폭락 시 '시장 안정자' 역할을 합니다.",
    styleTagsEn: ["Long-Term", "Diversified", "Institutional", "ESG-Aware"],
    styleTagsKo: ["장기 투자", "분산투자", "기관 투자", "ESG 고려"],
    lastUpdated: "Q3 2025",
    filingType: "공시 데이터 (Public Disclosure)",
    sectorAllocation: [
      { sector: "Technology", weight: 28.4, color: "#8b5cf6" },
      { sector: "Financials", weight: 18.7, color: "#3b82f6" },
      { sector: "Industrials", weight: 14.2, color: "#f59e0b" },
      { sector: "Consumer Discretionary", weight: 12.3, color: "#f97316" },
      { sector: "Materials", weight: 9.6, color: "#10b981" },
      { sector: "Healthcare", weight: 8.1, color: "#ef4444" },
      { sector: "Other", weight: 8.7, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "005930.KS", company: "삼성전자 (Samsung Electronics)", sector: "Technology", shares: 500000000, weight: 18.2, change: "Held", changePct: 0, whyTheyBoughtEn: "Samsung is Korea's largest company and a global leader in memory chips (DRAM, NAND) and smartphones. NPS holds Samsung as a strategic national asset.", whyTheyBoughtKo: "삼성은 한국 최대 기업이자 메모리 칩(DRAM, NAND)과 스마트폰의 글로벌 선도 기업입니다. 국민연금은 삼성을 전략적 국가 자산으로 보유합니다." },
      { ticker: "000660.KS", company: "SK하이닉스 (SK Hynix)", sector: "Technology", shares: 80000000, weight: 6.8, change: "Bought", changePct: 7.2, whyTheyBoughtEn: "SK Hynix is the world's second-largest memory chip maker, a key beneficiary of AI-driven HBM (High Bandwidth Memory) demand.", whyTheyBoughtKo: "SK하이닉스는 세계 2위 메모리 칩 제조업체로, AI 주도 HBM(고대역폭 메모리) 수요의 핵심 수혜자입니다." },
      { ticker: "005380.KS", company: "현대자동차 (Hyundai Motor)", sector: "Consumer Discretionary", shares: 25000000, weight: 5.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Hyundai has transformed into a global EV leader. Its Ioniq lineup competes directly with Tesla, and the Hyundai-Kia group ranks among global EV sales leaders.", whyTheyBoughtKo: "현대자동차는 글로벌 EV 리더로 변신했습니다. 아이오닉 라인업이 테슬라와 직접 경쟁하며 현대-기아 그룹은 글로벌 EV 판매 상위권에 올랐습니다." },
      { ticker: "035420.KS", company: "NAVER Corp.", sector: "Technology", shares: 10000000, weight: 3.4, change: "Sold", changePct: -8.5, whyTheyBoughtEn: "NAVER is South Korea's dominant search engine and internet ecosystem. LINE messaging, cloud services, and webtoon platform diversify revenue across Asia.", whyTheyBoughtKo: "네이버는 한국의 지배적인 검색 엔진 및 인터넷 생태계입니다. 라인, 클라우드, 웹툰 플랫폼이 아시아 전반에 걸쳐 수익을 다각화합니다." },
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 15000000, weight: 4.8, change: "Held", changePct: 0, whyTheyBoughtEn: "NPS holds Apple as part of its overseas allocation targeting global market leaders. Consistent earnings, dividend growth, and buybacks make it ideal for long-term pension funds.", whyTheyBoughtKo: "국민연금은 글로벌 시장 선도 기업을 대상으로 하는 해외 배분의 일환으로 애플을 보유합니다. 일관된 실적, 배당 성장, 자사주 매입이 장기 연금 펀드에 이상적입니다." },
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 8000000, weight: 3.6, change: "Bought", changePct: 5.4, whyTheyBoughtEn: "Microsoft's cloud and AI leadership makes it a core overseas holding. NPS increased its position as Azure AI services drove sustained revenue growth.", whyTheyBoughtKo: "마이크로소프트의 클라우드와 AI 리더십이 핵심 해외 보유 종목으로 만듭니다. Azure AI 서비스가 지속적인 매출 성장을 이끌면서 국민연금이 포지션을 늘렸습니다." },
    ],
  },

  {
    id: "gpif",
    name: "GPIF",
    firm: "Government Pension Investment Fund",
    country: "JP",
    aum: 1900,
    aumUnit: "T¥",
    initials: "GP",
    avatarColor: "#c2410c",
    category: "sovereign",
    biographyEn: "Japan's Government Pension Investment Fund is the world's largest pension fund, managing ¥225 trillion ($1.4T USD). Established to fund retirement benefits for Japan's aging population.",
    biographyKo: "일본의 정부연금투자기금은 225조 엔(약 1.4조 달러)을 운용하는 세계 최대 연금 기금입니다. 일본의 고령화 인구 퇴직 급여를 위해 설립되었습니다.",
    styleEn: "Passively managed across domestic/foreign equities and bonds with strict risk limits. Shifted from bonds to equities in 2014 to improve returns for Japan's aging population.",
    styleKo: "엄격한 위험 한도로 국내/해외 주식과 채권에 걸쳐 패시브 운용합니다. 일본 고령화 인구의 수익 개선을 위해 2014년 채권에서 주식으로 전환했습니다.",
    styleTagsEn: ["Passive", "Long-Term", "Diversified", "Government-Managed"],
    styleTagsKo: ["패시브", "장기", "분산투자", "정부 운용"],
    lastUpdated: "Q3 2025",
    filingType: "Quarterly Disclosure (Japan)",
    sectorAllocation: [
      { sector: "Domestic Bonds", weight: 25.0, color: "#3b82f6" },
      { sector: "Foreign Equities", weight: 25.0, color: "#8b5cf6" },
      { sector: "Domestic Equities", weight: 25.0, color: "#f59e0b" },
      { sector: "Foreign Bonds", weight: 21.0, color: "#10b981" },
      { sector: "Alternatives", weight: 4.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "7203.T", company: "Toyota Motor", sector: "Consumer", shares: 480000000, weight: 2.8, change: "Held", changePct: 0, whyTheyBoughtEn: "Toyota is Japan's largest company and a core domestic equity holding for GPIF. Its hydrogen fuel cell and hybrid leadership represent the future of mobility.", whyTheyBoughtKo: "토요타는 일본 최대 기업이자 GPIF의 핵심 국내 주식 보유 종목입니다. 수소연료전지와 하이브리드 리더십은 이동성의 미래를 대표합니다." },
      { ticker: "SPY", company: "SPDR S&P 500 ETF", sector: "Foreign Equities", shares: 82000000, weight: 8.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Core US equity exposure via ETF for GPIF's 25% foreign equity allocation. Low-cost index tracking aligned with GPIF's passive management mandate.", whyTheyBoughtKo: "GPIF의 25% 해외 주식 배분을 위한 ETF를 통한 핵심 미국 주식 노출입니다. 저비용 인덱스 추종이 GPIF의 패시브 운용 위임과 일치합니다." },
      { ticker: "9984.T", company: "SoftBank Group", sector: "Technology", shares: 220000000, weight: 2.1, change: "Held", changePct: 0, whyTheyBoughtEn: "SoftBank's Vision Fund provides exposure to global tech unicorns. GPIF holds SoftBank as part of domestic equity index, benefiting from AI portfolio company value.", whyTheyBoughtKo: "소프트뱅크의 비전 펀드는 글로벌 기술 유니콘에 노출을 제공합니다. GPIF는 AI 포트폴리오 기업 가치 혜택과 함께 국내 주식 지수의 일환으로 소프트뱅크를 보유합니다." },
    ],
  },

  {
    id: "gic",
    name: "GIC Singapore",
    firm: "GIC Private Limited",
    country: "SG",
    aum: 690,
    aumUnit: "B",
    initials: "GI",
    avatarColor: "#b45309",
    category: "sovereign",
    biographyEn: "GIC manages Singapore's foreign reserves and is one of the world's largest sovereign wealth funds, managing over $690B USD. It has a 20-year investment horizon and focuses on global long-term opportunities.",
    biographyKo: "GIC는 싱가포르의 외환 보유고를 관리하는 세계 최대 국부 펀드 중 하나로 6,900억 달러 이상을 운용합니다. 20년 투자 지평으로 글로벌 장기 기회에 집중합니다.",
    styleEn: "Globally diversified long-term investment approach. Targets private markets, real estate, and public equities with 20-year+ outlook. ESG integration across all asset classes.",
    styleKo: "전 세계적으로 분산된 장기 투자 접근법. 20년 이상의 관점으로 사모 시장, 부동산, 주식에 투자합니다. 모든 자산 클래스에 ESG를 통합합니다.",
    styleTagsEn: ["Long-Term", "Sovereign", "Private Markets", "Global Diversification"],
    styleTagsKo: ["장기", "국부 펀드", "사모 시장", "글로벌 분산"],
    lastUpdated: "Q3 2025",
    filingType: "Annual Report (Singapore)",
    sectorAllocation: [
      { sector: "Developed Equities", weight: 37.0, color: "#3b82f6" },
      { sector: "Private Equity", weight: 17.0, color: "#8b5cf6" },
      { sector: "Real Estate", weight: 10.0, color: "#f59e0b" },
      { sector: "Fixed Income", weight: 22.0, color: "#10b981" },
      { sector: "Infrastructure", weight: 8.0, color: "#ef4444" },
      { sector: "Cash & Others", weight: 6.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 22000000, weight: 4.2, change: "Bought", changePct: 8.4, whyTheyBoughtEn: "GIC's 20-year horizon perfectly aligns with Microsoft's AI cloud transformation. Azure AI will compound for decades as digital infrastructure becomes as essential as electricity.", whyTheyBoughtKo: "GIC의 20년 지평이 마이크로소프트의 AI 클라우드 전환과 완벽하게 일치합니다. 디지털 인프라가 전기처럼 필수적이 되면서 Azure AI가 수십 년간 복리 성장할 것입니다." },
      { ticker: "AMZN", company: "Amazon.com", sector: "Technology", shares: 18000000, weight: 3.8, change: "Held", changePct: 0, whyTheyBoughtEn: "Amazon's AWS is the dominant global cloud platform. GIC sees cloud computing as infrastructure of the next century, with Amazon's logistics and commerce amplifying the opportunity.", whyTheyBoughtKo: "아마존의 AWS는 지배적인 글로벌 클라우드 플랫폼입니다. GIC는 클라우드 컴퓨팅을 다음 세기의 인프라로 보며, 아마존의 물류와 상거래가 기회를 증폭시킵니다." },
    ],
  },

  {
    id: "temasek",
    name: "Temasek Holdings",
    firm: "Temasek Holdings Pte. Ltd.",
    country: "SG",
    aum: 380,
    aumUnit: "B",
    initials: "TH",
    avatarColor: "#9f1239",
    category: "sovereign",
    biographyEn: "Temasek is Singapore's state investment company, managing S$389B (≈$290B USD). Founded in 1974, it invests in both listed and unlisted companies with a long-term ownership mindset.",
    biographyKo: "테마섹은 싱가포르의 국영 투자 회사로 3,890억 싱가포르 달러(약 2,900억 달러)를 운용합니다. 1974년 설립되어 장기 소유 마인드로 상장 및 비상장 기업에 투자합니다.",
    styleEn: "Active ownership with a long-term perspective. Focuses on transformative megatrends: digitalization, sustainable living, longer lives, and emerging Asia growth.",
    styleKo: "장기적 관점의 적극적인 소유권. 디지털화, 지속 가능한 생활, 장수, 아시아 신흥 성장 등 변혁적 메가트렌드에 집중합니다.",
    styleTagsEn: ["Active Ownership", "Megatrends", "Asia Growth", "Long-Term"],
    styleTagsKo: ["적극적 소유권", "메가트렌드", "아시아 성장", "장기"],
    lastUpdated: "Q3 2025",
    filingType: "Annual Review (Singapore)",
    sectorAllocation: [
      { sector: "Financial Services", weight: 24.0, color: "#3b82f6" },
      { sector: "Technology", weight: 23.0, color: "#8b5cf6" },
      { sector: "Consumer", weight: 17.0, color: "#f59e0b" },
      { sector: "Industrials", weight: 11.0, color: "#10b981" },
      { sector: "Life Sciences", weight: 9.0, color: "#ef4444" },
      { sector: "Other", weight: 16.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "DBS.SI", company: "DBS Group Holdings", sector: "Financials", shares: 800000000, weight: 14.2, change: "Held", changePct: 0, whyTheyBoughtEn: "DBS is Southeast Asia's largest bank and a core strategic holding. Temasek supports Singapore's financial hub status through this anchor position.", whyTheyBoughtKo: "DBS는 동남아시아 최대 은행이자 핵심 전략적 보유 종목입니다. 테마섹은 이 앵커 포지션을 통해 싱가포르의 금융 허브 지위를 지원합니다." },
      { ticker: "SEA", company: "Sea Limited", sector: "Technology", shares: 42000000, weight: 6.8, change: "Bought", changePct: 22.4, whyTheyBoughtEn: "Sea Limited is Southeast Asia's largest internet company. Temasek's early investment in Garena/Shopee/SeaMoney reflects its bet on digital Southeast Asia's exponential growth.", whyTheyBoughtKo: "씨 리미티드는 동남아시아 최대 인터넷 회사입니다. 테마섹의 조기 투자는 가레나/쇼피/씨머니를 통한 디지털 동남아시아의 지수적 성장에 대한 베팅을 반영합니다." },
    ],
  },

  {
    id: "nbim",
    name: "Norway Pension Fund",
    firm: "Norges Bank Investment Mgmt",
    country: "NO",
    aum: 1800,
    aumUnit: "B",
    initials: "NB",
    avatarColor: "#1d4ed8",
    category: "sovereign",
    biographyEn: "Norway's Government Pension Fund Global (NBIM) is the world's largest sovereign wealth fund at $1.8T USD. Built from North Sea oil revenues, it now owns an average of 1.5% of every listed company globally.",
    biographyKo: "노르웨이의 정부연금기금 글로벌(NBIM)은 1.8조 달러로 세계 최대 국부 펀드입니다. 북해 석유 수입으로 조성되어 현재 전 세계 모든 상장 기업의 평균 1.5%를 소유합니다.",
    styleEn: "Passive, rules-based investing across 70+ countries with active exclusions for ESG violations. Owns a slice of virtually every publicly traded company globally.",
    styleKo: "ESG 위반에 대한 적극적 제외와 함께 70개 이상의 국가에서 규칙 기반 패시브 투자. 전 세계 거의 모든 상장 기업의 일부를 소유합니다.",
    styleTagsEn: ["Passive", "ESG Leader", "Global Diversification", "Sovereign"],
    styleTagsKo: ["패시브", "ESG 선도자", "글로벌 분산", "국부 펀드"],
    lastUpdated: "Q3 2025",
    filingType: "Annual Report (Norway)",
    sectorAllocation: [
      { sector: "Equities", weight: 70.0, color: "#3b82f6" },
      { sector: "Fixed Income", weight: 27.0, color: "#10b981" },
      { sector: "Real Estate", weight: 2.5, color: "#f59e0b" },
      { sector: "Renewables", weight: 0.5, color: "#22c55e" },
    ],
    holdings: [
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 180000000, weight: 1.2, change: "Held", changePct: 0, whyTheyBoughtEn: "NBIM owns Apple as part of its global equity index. As a top 10 global market cap company, Apple represents a core passive holding across NBIM's equity mandate.", whyTheyBoughtKo: "NBIM은 글로벌 주식 지수의 일환으로 애플을 보유합니다. 세계 10대 시가총액 기업으로서 애플은 NBIM의 주식 위임 전반에 걸친 핵심 패시브 보유 종목입니다." },
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 164000000, weight: 1.1, change: "Held", changePct: 0, whyTheyBoughtEn: "Microsoft is one of NBIM's largest single holdings globally. The fund passively tracks global indices, and Microsoft's dominant market cap makes it a top position automatically.", whyTheyBoughtKo: "마이크로소프트는 NBIM의 전 세계 최대 단일 보유 종목 중 하나입니다. 펀드가 글로벌 지수를 패시브 추종하며 마이크로소프트의 지배적 시가총액이 자동으로 최대 포지션이 됩니다." },
    ],
  },

  {
    id: "adia",
    name: "ADIA",
    firm: "Abu Dhabi Investment Authority",
    country: "AE",
    aum: 1000,
    aumUnit: "B",
    initials: "AD",
    avatarColor: "#065f46",
    category: "sovereign",
    biographyEn: "The Abu Dhabi Investment Authority is one of the world's largest sovereign wealth funds, managing over $1 trillion. It invests UAE's oil revenues for future generations.",
    biographyKo: "아부다비투자청은 1조 달러 이상을 운용하는 세계 최대 국부 펀드 중 하나입니다. UAE의 석유 수입을 미래 세대를 위해 투자합니다.",
    styleEn: "Global multi-asset class investing across listed equities, alternatives, real estate, and infrastructure. Very long-term perspective (decades) with increasing tech and emerging market exposure.",
    styleKo: "상장 주식, 대체 자산, 부동산, 인프라에 걸친 글로벌 다자산 클래스 투자. 기술 및 신흥시장 노출을 확대하는 매우 장기적(수십 년) 관점.",
    styleTagsEn: ["Sovereign", "Multi-Asset", "Oil Revenue", "Generational"],
    styleTagsKo: ["국부 펀드", "다자산", "석유 수입", "세대를 위한"],
    lastUpdated: "Q3 2025",
    filingType: "Annual Report",
    sectorAllocation: [
      { sector: "Developed Equities", weight: 32.0, color: "#3b82f6" },
      { sector: "Emerging Equities", weight: 18.0, color: "#f59e0b" },
      { sector: "Fixed Income", weight: 17.0, color: "#10b981" },
      { sector: "Private Equity", weight: 12.0, color: "#8b5cf6" },
      { sector: "Real Estate", weight: 8.0, color: "#ef4444" },
      { sector: "Infrastructure", weight: 8.0, color: "#f97316" },
      { sector: "Other", weight: 5.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AMZN", company: "Amazon.com", sector: "Technology", shares: 24000000, weight: 2.1, change: "Bought", changePct: 12.4, whyTheyBoughtEn: "ADIA's secular growth mandate targets Amazon as the dominant global commerce and cloud infrastructure company for the next century.", whyTheyBoughtKo: "ADIA의 장기 성장 위임은 아마존을 다음 세기의 지배적인 글로벌 상거래 및 클라우드 인프라 회사로 선정합니다." },
    ],
  },

  {
    id: "pif",
    name: "Saudi Arabia PIF",
    firm: "Public Investment Fund",
    country: "SA",
    aum: 925,
    aumUnit: "B",
    initials: "PF",
    avatarColor: "#15803d",
    category: "sovereign",
    biographyEn: "Saudi Arabia's Public Investment Fund is one of the fastest-growing sovereign wealth funds. Led by Crown Prince MBS, it aims to diversify Saudi Arabia's economy beyond oil through Vision 2030.",
    biographyKo: "사우디아라비아의 공공투자펀드는 가장 빠르게 성장하는 국부 펀드 중 하나입니다. 왕세자 MBS가 이끌며 비전 2030을 통해 사우디 경제를 석유 너머로 다각화하는 것을 목표로 합니다.",
    styleEn: "Aggressive global investment strategy with focus on Vision 2030 diversification. High-profile investments in sports (Newcastle, LIV Golf), tech, and gaming alongside traditional finance.",
    styleKo: "비전 2030 다각화에 초점을 맞춘 공격적인 글로벌 투자 전략. 전통 금융과 함께 스포츠(뉴캐슬, LIV 골프), 기술, 게임에 고프로파일 투자합니다.",
    styleTagsEn: ["Vision 2030", "Diversification", "Sports & Entertainment", "Tech"],
    styleTagsKo: ["비전 2030", "다각화", "스포츠 & 엔터", "기술"],
    lastUpdated: "Q3 2025",
    filingType: "Annual Report",
    sectorAllocation: [
      { sector: "Financial Services", weight: 22.0, color: "#3b82f6" },
      { sector: "Technology", weight: 18.0, color: "#8b5cf6" },
      { sector: "Real Estate", weight: 16.0, color: "#f59e0b" },
      { sector: "Entertainment", weight: 12.0, color: "#ec4899" },
      { sector: "Industrials", weight: 18.0, color: "#10b981" },
      { sector: "Other", weight: 14.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "UBER", company: "Uber Technologies", sector: "Technology", shares: 160000000, weight: 8.4, change: "Held", changePct: 0, whyTheyBoughtEn: "PIF made a massive early bet on Uber, betting on ride-sharing becoming global infrastructure. Aligns with Vision 2030's smart mobility and non-oil economy goals.", whyTheyBoughtKo: "PIF는 라이드쉐어가 글로벌 인프라가 될 것이라는 베팅으로 우버에 대규모 초기 투자를 했습니다. 비전 2030의 스마트 이동성 및 비석유 경제 목표와 일치합니다." },
      { ticker: "NTDOY", company: "Nintendo", sector: "Technology", shares: 42000000, weight: 6.2, change: "Bought", changePct: 14.8, whyTheyBoughtEn: "PIF has been aggressively acquiring gaming assets. Nintendo's IP (Mario, Zelda, Pokemon) is unmatched and the Switch platform shows hardware + software synergy.", whyTheyBoughtKo: "PIF는 게임 자산을 공격적으로 확보하고 있습니다. 닌텐도의 IP(마리오, 젤다, 포켓몬)는 타의 추종을 불허하며 스위치 플랫폼은 하드웨어+소프트웨어 시너지를 보여줍니다." },
    ],
  },

  {
    id: "calpers",
    name: "CalPERS",
    firm: "California Public Employees' Retirement System",
    country: "US",
    aum: 500,
    aumUnit: "B",
    initials: "CP",
    avatarColor: "#1e3a5f",
    category: "sovereign",
    biographyEn: "CalPERS is the largest US public pension fund, managing $500B+ for California's public employees. It is a leader in ESG investing and corporate governance activism.",
    biographyKo: "캘퍼스는 캘리포니아 공무원을 위해 5,000억 달러 이상을 운용하는 미국 최대 공적 연금 기금입니다. ESG 투자와 기업 지배구조 행동주의의 선두주자입니다.",
    styleEn: "Diversified institutional investing with significant ESG focus. Known for shareholder activism on corporate governance issues and climate change disclosure requirements.",
    styleKo: "상당한 ESG 중심의 분산 기관 투자. 기업 지배구조 문제와 기후변화 공시 요건에 대한 주주 행동주의로 유명합니다.",
    styleTagsEn: ["ESG Pioneer", "Corporate Governance", "Diversified", "Activist Shareholder"],
    styleTagsKo: ["ESG 선도", "기업 지배구조", "분산투자", "행동주의 주주"],
    lastUpdated: "Q3 2025",
    filingType: "Public Pension Disclosure",
    sectorAllocation: [
      { sector: "Global Equities", weight: 42.0, color: "#3b82f6" },
      { sector: "Fixed Income", weight: 28.0, color: "#10b981" },
      { sector: "Private Equity", weight: 14.0, color: "#8b5cf6" },
      { sector: "Real Estate", weight: 10.0, color: "#f59e0b" },
      { sector: "Infrastructure", weight: 6.0, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 64000000, weight: 2.4, change: "Held", changePct: 0, whyTheyBoughtEn: "CalPERS holds Apple across its global equity mandate. It also engages Apple on supply chain labor practices and environmental commitments as part of its governance role.", whyTheyBoughtKo: "캘퍼스는 글로벌 주식 위임 전반에 걸쳐 애플을 보유합니다. 또한 지배구조 역할의 일환으로 공급망 노동 관행과 환경 약속에 대해 애플과 관여합니다." },
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 58000000, weight: 2.2, change: "Held", changePct: 0, whyTheyBoughtEn: "Microsoft scores highly on CalPERS's ESG metrics — strong climate commitments, employee diversity, and governance. Also a core index holding.", whyTheyBoughtKo: "마이크로소프트는 캘퍼스의 ESG 지표에서 높은 점수를 받습니다 — 강한 기후 약속, 직원 다양성, 지배구조. 또한 핵심 지수 보유 종목입니다." },
    ],
  },

  // ─── INDEX / PASSIVE ────────────────────────────────────────────────────────
  {
    id: "blackrock",
    name: "BlackRock",
    firm: "BlackRock Inc.",
    country: "US",
    aum: 10000,
    aumUnit: "B",
    initials: "BR",
    avatarColor: "#1e293b",
    category: "index",
    biographyEn: "BlackRock is the world's largest asset manager with $10T+ AUM. Founded by Larry Fink in 1988, it pioneered exchange-traded funds (ETFs) through its iShares platform and revolutionized passive investing.",
    biographyKo: "블랙록은 10조 달러 이상의 자산을 운용하는 세계 최대 자산운용사입니다. 1988년 래리 핑크가 설립하여 iShares 플랫폼을 통해 ETF를 개척하고 패시브 투자를 혁신했습니다.",
    styleEn: "Passive index management combined with active management. iShares ETFs track virtually every global index. Aladdin risk management system underpins $20T+ in assets globally.",
    styleKo: "패시브 인덱스 운용과 액티브 운용을 결합합니다. iShares ETF는 거의 모든 글로벌 지수를 추종합니다. 알라딘 리스크 관리 시스템이 전 세계 20조 달러 이상의 자산을 뒷받침합니다.",
    styleTagsEn: ["Passive Giant", "ETF Pioneer", "Scale Advantage", "iShares"],
    styleTagsKo: ["패시브 거물", "ETF 개척자", "규모 우위", "iShares"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 28.4, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 14.2, color: "#ef4444" },
      { sector: "Financials", weight: 13.8, color: "#3b82f6" },
      { sector: "Consumer", weight: 12.4, color: "#f59e0b" },
      { sector: "Industrials", weight: 9.6, color: "#10b981" },
      { sector: "Other", weight: 21.6, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 900000000, weight: 5.8, change: "Held", changePct: 0, whyTheyBoughtEn: "BlackRock holds Apple primarily through index funds tracking S&P 500, MSCI World, and other major indices. At $3T+ market cap, Apple is the largest weight in most global indices.", whyTheyBoughtKo: "블랙록은 S&P 500, MSCI 세계 지수 등 주요 지수를 추종하는 인덱스 펀드를 통해 주로 애플을 보유합니다. 3조 달러 이상의 시가총액으로 대부분의 글로벌 지수에서 최대 비중입니다." },
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 820000000, weight: 5.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Microsoft is the second-largest holding across BlackRock's index funds. Its index weight reflects both market leadership and the passive investment revolution BlackRock pioneered.", whyTheyBoughtKo: "마이크로소프트는 블랙록의 인덱스 펀드 전반에서 두 번째로 큰 보유 종목입니다. 지수 비중은 시장 리더십과 블랙록이 개척한 패시브 투자 혁명을 반영합니다." },
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 620000000, weight: 4.2, change: "Bought", changePct: 18.4, whyTheyBoughtEn: "NVIDIA's explosive weight gains in S&P 500 and Nasdaq indices automatically increase BlackRock's holdings as index weights rebalance to reflect NVIDIA's surging market cap.", whyTheyBoughtKo: "엔비디아의 S&P 500과 나스닥 지수 비중 폭발적 증가로 시가총액 급등에 맞춰 지수 비중이 재조정되면서 블랙록의 보유량이 자동으로 증가했습니다." },
    ],
  },

  {
    id: "vanguard",
    name: "Vanguard Group",
    firm: "The Vanguard Group",
    country: "US",
    aum: 8500,
    aumUnit: "B",
    initials: "VG",
    avatarColor: "#7c2d12",
    category: "index",
    biographyEn: "Vanguard was founded by John Bogle in 1975 as the world's first index mutual fund company. Its unique investor-owned structure means profits are returned to investors as lower fees — revolutionizing personal finance.",
    biographyKo: "뱅가드는 1975년 존 보글에 의해 세계 최초 인덱스 뮤추얼 펀드 회사로 설립되었습니다. 독특한 투자자 소유 구조로 수익이 낮은 수수료로 투자자에게 환원됩니다 — 개인 금융을 혁신했습니다.",
    styleEn: "Pure passive index investing at lowest possible cost. Vanguard's investor-owned structure eliminates profit motives, enabling the lowest expense ratios in the industry.",
    styleKo: "가능한 가장 낮은 비용의 순수 패시브 인덱스 투자. 뱅가드의 투자자 소유 구조가 이익 동기를 제거하여 업계에서 가장 낮은 비용 비율을 가능하게 합니다.",
    styleTagsEn: ["Ultra Low Cost", "Passive Pioneer", "Investor-Owned", "Long-Term"],
    styleTagsKo: ["초저비용", "패시브 개척자", "투자자 소유", "장기"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 29.2, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 13.4, color: "#ef4444" },
      { sector: "Financials", weight: 13.1, color: "#3b82f6" },
      { sector: "Consumer", weight: 12.8, color: "#f59e0b" },
      { sector: "Industrials", weight: 9.8, color: "#10b981" },
      { sector: "Other", weight: 21.7, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 1280000000, weight: 6.2, change: "Held", changePct: 0, whyTheyBoughtEn: "Vanguard holds Apple across total market and S&P 500 index funds. Bogle's philosophy: own the market, not pick stocks. Apple's dominant index weight means every Vanguard investor owns Apple.", whyTheyBoughtKo: "뱅가드는 전체 시장 및 S&P 500 인덱스 펀드 전반에 걸쳐 애플을 보유합니다. 보글의 철학: 종목을 선택하지 말고 시장을 소유하라. 애플의 지배적 지수 비중이 모든 뱅가드 투자자가 애플을 소유함을 의미합니다." },
      { ticker: "MSFT", company: "Microsoft Corp.", sector: "Technology", shares: 1180000000, weight: 5.8, change: "Held", changePct: 0, whyTheyBoughtEn: "Microsoft is Vanguard's second-largest equity holding globally. Every VTI, VOO, and VTSAX holder automatically owns Microsoft shares proportional to its market cap weight.", whyTheyBoughtKo: "마이크로소프트는 뱅가드의 전 세계 두 번째로 큰 주식 보유 종목입니다. 모든 VTI, VOO, VTSAX 보유자는 시가총액 비중에 비례하여 자동으로 마이크로소프트 주식을 보유합니다." },
    ],
  },

  {
    id: "statestreet",
    name: "State Street SSGA",
    firm: "State Street Global Advisors",
    country: "US",
    aum: 4400,
    aumUnit: "B",
    initials: "SS",
    avatarColor: "#374151",
    category: "index",
    biographyEn: "State Street Global Advisors created the world's first US ETF — the SPDR S&P 500 ETF (SPY) in 1993. The iconic 'Fearless Girl' statue outside its NYC office represents its commitment to board gender diversity.",
    biographyKo: "스테이트 스트리트 글로벌 어드바이저스는 1993년 세계 최초의 미국 ETF인 SPDR S&P 500 ETF(SPY)를 만들었습니다. 뉴욕 사무소 앞의 상징적인 '두려움 없는 소녀' 동상은 이사회 성별 다양성에 대한 헌신을 나타냅니다.",
    styleEn: "Passive ETF investing with active engagement on ESG issues. Creator of SPY and SPDR family of ETFs. Strong governance engagement via proxy voting on diversity and climate.",
    styleKo: "ESG 문제에 적극적인 관여를 하는 패시브 ETF 투자. SPY와 SPDR ETF 패밀리의 창시자. 다양성과 기후에 대한 의결권 행사를 통한 강력한 지배구조 관여.",
    styleTagsEn: ["ETF Creator", "ESG Engagement", "Governance", "Passive"],
    styleTagsKo: ["ETF 창시자", "ESG 관여", "지배구조", "패시브"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 27.8, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 13.6, color: "#ef4444" },
      { sector: "Financials", weight: 13.2, color: "#3b82f6" },
      { sector: "Consumer", weight: 12.1, color: "#f59e0b" },
      { sector: "Industrials", weight: 9.4, color: "#10b981" },
      { sector: "Other", weight: 23.9, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "SPY", company: "SPDR S&P 500 ETF", sector: "ETFs", shares: 1000000000, weight: 15.2, change: "Held", changePct: 0, whyTheyBoughtEn: "State Street created SPY — the world's first ETF and still its flagship product. Managing SPY is both a core business and the embodiment of Bogle-inspired passive investing.", whyTheyBoughtKo: "스테이트 스트리트는 세계 최초이자 여전히 주력 상품인 SPY ETF를 만들었습니다. SPY 운용은 핵심 사업이자 보글에서 영감을 받은 패시브 투자의 구현입니다." },
    ],
  },

  {
    id: "fidelity",
    name: "Fidelity Investments",
    firm: "Fidelity Management & Research",
    country: "US",
    aum: 5800,
    aumUnit: "B",
    initials: "FI",
    avatarColor: "#065f46",
    category: "index",
    biographyEn: "Fidelity is famous for the legendary Peter Lynch, who ran the Magellan Fund and beat the market for 13 consecutive years. Today it manages $5.8T including both active and passive strategies.",
    biographyKo: "피델리티는 마젤란 펀드를 운용하며 13년 연속 시장을 이긴 전설적인 피터 린치로 유명합니다. 오늘날 액티브와 패시브 전략을 포함하여 5.8조 달러를 운용합니다.",
    styleEn: "Hybrid active/passive manager. Active funds use fundamental bottom-up stock picking, while passive tracks indices. Known for zero-fee index funds that disrupted the industry.",
    styleKo: "하이브리드 액티브/패시브 운용사. 액티브 펀드는 기본적 상향식 종목 선정을 사용하며, 패시브는 지수를 추종합니다. 업계를 파괴한 수수료 제로 인덱스 펀드로 유명합니다.",
    styleTagsEn: ["Active + Passive", "Zero-Fee Funds", "Stock Research", "Long-Term"],
    styleTagsKo: ["액티브 + 패시브", "수수료 제로", "주식 리서치", "장기"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 30.4, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 14.8, color: "#ef4444" },
      { sector: "Financials", weight: 12.7, color: "#3b82f6" },
      { sector: "Consumer", weight: 12.2, color: "#f59e0b" },
      { sector: "Industrials", weight: 9.1, color: "#10b981" },
      { sector: "Other", weight: 20.8, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AAPL", company: "Apple Inc.", sector: "Technology", shares: 420000000, weight: 5.4, change: "Held", changePct: 0, whyTheyBoughtEn: "Fidelity's active funds like Contrafund and Growth Company have long owned Apple. Active managers recognize Apple's ecosystem lock-in and cash generation as durable competitive advantages.", whyTheyBoughtKo: "피델리티의 컨트라펀드와 그로스 컴퍼니 같은 액티브 펀드들이 오랫동안 애플을 보유했습니다. 액티브 운용자들은 애플의 생태계 잠금과 현금 창출을 지속적인 경쟁 우위로 인정합니다." },
      { ticker: "NVDA", company: "NVIDIA Corporation", sector: "Technology", shares: 280000000, weight: 4.8, change: "Bought", changePct: 24.2, whyTheyBoughtEn: "Fidelity's tech-focused active funds dramatically increased NVIDIA exposure as AI spending became clear. Fund managers see NVIDIA's data center growth compounding for years.", whyTheyBoughtKo: "AI 지출이 명확해지면서 피델리티의 기술 중심 액티브 펀드들이 엔비디아 노출을 크게 확대했습니다. 펀드 운용자들은 엔비디아의 데이터센터 성장이 수년간 복리 성장한다고 봅니다." },
    ],
  },

  {
    id: "troweprice",
    name: "T. Rowe Price",
    firm: "T. Rowe Price Group",
    country: "US",
    aum: 1600,
    aumUnit: "B",
    initials: "TR",
    avatarColor: "#1e40af",
    category: "index",
    biographyEn: "T. Rowe Price was founded by Thomas Rowe Price Jr. in 1937, pioneering growth investing. The Baltimore-based manager is known for deep fundamental research and long-term growth-oriented active management.",
    biographyKo: "T. 로우 프라이스는 1937년 토마스 로우 프라이스 주니어가 성장 투자를 개척하며 설립했습니다. 볼티모어 기반 운용사는 심층적인 기본 리서치와 장기 성장 지향 액티브 운용으로 유명합니다.",
    styleEn: "Growth-oriented active management with deep fundamental research. Long-term investors with low portfolio turnover. Pioneered investing in growth companies before they became household names.",
    styleKo: "심층 기본 리서치를 갖춘 성장 지향 액티브 운용. 낮은 포트폴리오 회전율의 장기 투자자들. 잘 알려지기 전에 성장 기업에 투자하는 것을 개척했습니다.",
    styleTagsEn: ["Growth Investing", "Active Research", "Low Turnover", "Long-Term"],
    styleTagsKo: ["성장 투자", "액티브 리서치", "낮은 회전율", "장기"],
    lastUpdated: "Q3 2025",
    filingType: "13F Filing (SEC)",
    sectorAllocation: [
      { sector: "Technology", weight: 32.8, color: "#8b5cf6" },
      { sector: "Healthcare", weight: 16.4, color: "#ef4444" },
      { sector: "Financials", weight: 12.2, color: "#3b82f6" },
      { sector: "Consumer", weight: 14.6, color: "#f59e0b" },
      { sector: "Industrials", weight: 9.8, color: "#10b981" },
      { sector: "Other", weight: 14.2, color: "#6b7280" },
    ],
    holdings: [
      { ticker: "AMZN", company: "Amazon.com", sector: "Technology", shares: 180000000, weight: 5.8, change: "Held", changePct: 0, whyTheyBoughtEn: "T. Rowe Price was an early Amazon investor in the 1990s and held through massive drawdowns. Their research identified Amazon's reinvestment flywheel decades before consensus understood it.", whyTheyBoughtKo: "T. 로우 프라이스는 1990년대 초기 아마존 투자자였으며 대규모 하락에도 보유했습니다. 리서치가 컨센서스가 이해하기 수십 년 전에 아마존의 재투자 플라이휠을 식별했습니다." },
      { ticker: "META", company: "Meta Platforms", sector: "Technology", shares: 68000000, weight: 4.2, change: "Bought", changePct: 22.4, whyTheyBoughtEn: "T. Rowe Price increased Meta during the 2022 drawdown when metaverse spending scared investors. They recognized the core advertising business remained dominant despite management distraction.", whyTheyBoughtKo: "T. 로우 프라이스는 메타버스 지출이 투자자를 놀라게 한 2022년 하락 시 메타를 늘렸습니다. 경영진의 주의 분산에도 불구하고 핵심 광고 사업이 지배적으로 유지됨을 인식했습니다." },
    ],
  },
];

export function getSuperInvestorById(id: string): SuperInvestor | undefined {
  return SUPER_INVESTORS.find((inv) => inv.id === id);
}

export function getSuperInvestorsByCategory(category: InvestorCategory): SuperInvestor[] {
  return SUPER_INVESTORS.filter((inv) => inv.category === category);
}
